/********************************************************************************
** Form generated from reading UI file 'netpan.ui'
**
** Created by: Qt User Interface Compiler version 6.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NETPAN_H
#define UI_NETPAN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_netpan
{
public:
    QPushButton *btn_1_6;
    QPushButton *btn_2_3;
    QPushButton *btn_7_5;
    QPushButton *btn_1_7;
    QPushButton *btn_5_5;
    QPushButton *btn_3_6;
    QPushButton *btn_1_0;
    QPushButton *btn_8_8;
    QPushButton *btn_8_3;
    QPushButton *btn_1_2;
    QPushButton *btn_8_5;
    QPushButton *btn_lose;
    QLineEdit *line_player_0;
    QPushButton *btn_4_1;
    QPushButton *btn_7_2;
    QPushButton *btn_5_8;
    QPushButton *btn_6_6;
    QPushButton *btn_startgame;
    QPushButton *btn_3_3;
    QPushButton *btn_6_5;
    QPushButton *btn_2_7;
    QPushButton *btn_6_4;
    QPushButton *btn_2_5;
    QPushButton *btn_2_1;
    QPushButton *btn_3_0;
    QPushButton *btn_0_1;
    QPushButton *btn_0_3;
    QPushButton *btn_5_1;
    QPushButton *btn_6_1;
    QPushButton *btn_1_5;
    QPushButton *btn_5_4;
    QPushButton *btn_7_8;
    QPushButton *btn_8_7;
    QPushButton *btn_2_4;
    QPushButton *btn_8_1;
    QLineEdit *txtl_pan_time;
    QPushButton *btn_3_5;
    QLabel *label;
    QPushButton *btn_2_0;
    QPushButton *btn_2_2;
    QPushButton *btn_5_0;
    QPushButton *btn_2_8;
    QPushButton *btn_4_6;
    QPushButton *btn_white;
    QPushButton *btn_7_3;
    QPushButton *btn_5_6;
    QPushButton *btn_2_6;
    QPushButton *btn_0_2;
    QPushButton *btn_1_1;
    QPushButton *btn_4_5;
    QPushButton *btn_3_4;
    QPushButton *btn_6_7;
    QPushButton *btn_4_7;
    QPushButton *btn_4_0;
    QPushButton *btn_8_0;
    QPushButton *btn_3_2;
    QPushButton *btn_0_0;
    QPushButton *btn_3_8;
    QPushButton *btn_0_7;
    QLabel *label_3;
    QPushButton *btn_7_1;
    QPushButton *btn_black;
    QPushButton *btn_0_5;
    QPushButton *btn_6_0;
    QPushButton *btn_0_4;
    QPushButton *btn_7_7;
    QPushButton *btn_4_2;
    QPushButton *btn_6_3;
    QPushButton *btn_5_7;
    QPushButton *btn_7_0;
    QPushButton *btn_6_8;
    QPushButton *btn_4_4;
    QPushButton *btn_4_3;
    QPushButton *btn_8_6;
    QPushButton *btn_6_2;
    QPushButton *btn_7_6;
    QPushButton *btn_stop;
    QPushButton *back;
    QPushButton *btn_3_7;
    QPushButton *btn_8_2;
    QPushButton *btn_1_8;
    QPushButton *btn_5_2;
    QLineEdit *line_player_1;
    QPushButton *btn_0_8;
    QPushButton *btn_7_4;
    QPushButton *btn_4_8;
    QPushButton *btn_0_6;
    QPushButton *btn_1_3;
    QPushButton *btn_3_1;
    QPushButton *btn_5_3;
    QPushButton *btn_1_4;
    QPushButton *btn_8_4;
    QPushButton *sendbtn;
    QLineEdit *Chatline;
    QPlainTextEdit *Chatplain;
    QLineEdit *PORTEdit;
    QPushButton *reSetButton;
    QLabel *label_2;
    QLabel *label_4;
    QPushButton *reStartButton;
    QLabel *connectLabel;
    QPushButton *reConnectButton;
    QLineEdit *IPEdit;
    QWidget *widget;
    QHBoxLayout *horizontalLayout;
    QLabel *label_5;
    QRadioButton *choseb;
    QRadioButton *chosew;

    void setupUi(QWidget *netpan)
    {
        if (netpan->objectName().isEmpty())
            netpan->setObjectName(QString::fromUtf8("netpan"));
        netpan->resize(1200, 720);
        btn_1_6 = new QPushButton(netpan);
        btn_1_6->setObjectName(QString::fromUtf8("btn_1_6"));
        btn_1_6->setEnabled(true);
        btn_1_6->setGeometry(QRect(570, 190, 50, 50));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btn_1_6->sizePolicy().hasHeightForWidth());
        btn_1_6->setSizePolicy(sizePolicy);
        btn_1_6->setMinimumSize(QSize(50, 50));
        btn_1_6->setMaximumSize(QSize(60, 50));
        btn_1_6->setStyleSheet(QString::fromUtf8(""));
        btn_1_6->setFlat(false);
        btn_2_3 = new QPushButton(netpan);
        btn_2_3->setObjectName(QString::fromUtf8("btn_2_3"));
        btn_2_3->setEnabled(true);
        btn_2_3->setGeometry(QRect(420, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_3->sizePolicy().hasHeightForWidth());
        btn_2_3->setSizePolicy(sizePolicy);
        btn_2_3->setMinimumSize(QSize(50, 50));
        btn_2_3->setMaximumSize(QSize(60, 50));
        btn_2_3->setStyleSheet(QString::fromUtf8(""));
        btn_2_3->setFlat(false);
        btn_7_5 = new QPushButton(netpan);
        btn_7_5->setObjectName(QString::fromUtf8("btn_7_5"));
        btn_7_5->setEnabled(true);
        btn_7_5->setGeometry(QRect(520, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_5->sizePolicy().hasHeightForWidth());
        btn_7_5->setSizePolicy(sizePolicy);
        btn_7_5->setMinimumSize(QSize(50, 50));
        btn_7_5->setMaximumSize(QSize(60, 50));
        btn_7_5->setStyleSheet(QString::fromUtf8(""));
        btn_7_5->setFlat(false);
        btn_1_7 = new QPushButton(netpan);
        btn_1_7->setObjectName(QString::fromUtf8("btn_1_7"));
        btn_1_7->setEnabled(true);
        btn_1_7->setGeometry(QRect(620, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_7->sizePolicy().hasHeightForWidth());
        btn_1_7->setSizePolicy(sizePolicy);
        btn_1_7->setMinimumSize(QSize(50, 50));
        btn_1_7->setMaximumSize(QSize(60, 50));
        btn_1_7->setStyleSheet(QString::fromUtf8(""));
        btn_1_7->setFlat(false);
        btn_5_5 = new QPushButton(netpan);
        btn_5_5->setObjectName(QString::fromUtf8("btn_5_5"));
        btn_5_5->setEnabled(true);
        btn_5_5->setGeometry(QRect(520, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_5->sizePolicy().hasHeightForWidth());
        btn_5_5->setSizePolicy(sizePolicy);
        btn_5_5->setMinimumSize(QSize(50, 50));
        btn_5_5->setMaximumSize(QSize(60, 50));
        btn_5_5->setStyleSheet(QString::fromUtf8(""));
        btn_5_5->setFlat(false);
        btn_3_6 = new QPushButton(netpan);
        btn_3_6->setObjectName(QString::fromUtf8("btn_3_6"));
        btn_3_6->setEnabled(true);
        btn_3_6->setGeometry(QRect(570, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_6->sizePolicy().hasHeightForWidth());
        btn_3_6->setSizePolicy(sizePolicy);
        btn_3_6->setMinimumSize(QSize(50, 50));
        btn_3_6->setMaximumSize(QSize(60, 50));
        btn_3_6->setStyleSheet(QString::fromUtf8(""));
        btn_3_6->setFlat(false);
        btn_1_0 = new QPushButton(netpan);
        btn_1_0->setObjectName(QString::fromUtf8("btn_1_0"));
        btn_1_0->setEnabled(true);
        btn_1_0->setGeometry(QRect(270, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_0->sizePolicy().hasHeightForWidth());
        btn_1_0->setSizePolicy(sizePolicy);
        btn_1_0->setMinimumSize(QSize(50, 50));
        btn_1_0->setMaximumSize(QSize(60, 50));
        btn_1_0->setStyleSheet(QString::fromUtf8(""));
        btn_1_0->setFlat(false);
        btn_8_8 = new QPushButton(netpan);
        btn_8_8->setObjectName(QString::fromUtf8("btn_8_8"));
        btn_8_8->setEnabled(true);
        btn_8_8->setGeometry(QRect(670, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_8->sizePolicy().hasHeightForWidth());
        btn_8_8->setSizePolicy(sizePolicy);
        btn_8_8->setMinimumSize(QSize(50, 50));
        btn_8_8->setMaximumSize(QSize(50, 50));
        btn_8_8->setStyleSheet(QString::fromUtf8(""));
        btn_8_8->setFlat(false);
        btn_8_3 = new QPushButton(netpan);
        btn_8_3->setObjectName(QString::fromUtf8("btn_8_3"));
        btn_8_3->setEnabled(true);
        btn_8_3->setGeometry(QRect(420, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_3->sizePolicy().hasHeightForWidth());
        btn_8_3->setSizePolicy(sizePolicy);
        btn_8_3->setMinimumSize(QSize(50, 50));
        btn_8_3->setMaximumSize(QSize(60, 50));
        btn_8_3->setStyleSheet(QString::fromUtf8(""));
        btn_8_3->setFlat(false);
        btn_1_2 = new QPushButton(netpan);
        btn_1_2->setObjectName(QString::fromUtf8("btn_1_2"));
        btn_1_2->setEnabled(true);
        btn_1_2->setGeometry(QRect(370, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_2->sizePolicy().hasHeightForWidth());
        btn_1_2->setSizePolicy(sizePolicy);
        btn_1_2->setMinimumSize(QSize(50, 50));
        btn_1_2->setMaximumSize(QSize(60, 50));
        btn_1_2->setStyleSheet(QString::fromUtf8(""));
        btn_1_2->setFlat(false);
        btn_8_5 = new QPushButton(netpan);
        btn_8_5->setObjectName(QString::fromUtf8("btn_8_5"));
        btn_8_5->setEnabled(true);
        btn_8_5->setGeometry(QRect(520, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_5->sizePolicy().hasHeightForWidth());
        btn_8_5->setSizePolicy(sizePolicy);
        btn_8_5->setMinimumSize(QSize(50, 50));
        btn_8_5->setMaximumSize(QSize(60, 50));
        btn_8_5->setStyleSheet(QString::fromUtf8(""));
        btn_8_5->setFlat(false);
        btn_lose = new QPushButton(netpan);
        btn_lose->setObjectName(QString::fromUtf8("btn_lose"));
        btn_lose->setGeometry(QRect(790, 330, 91, 61));
        line_player_0 = new QLineEdit(netpan);
        line_player_0->setObjectName(QString::fromUtf8("line_player_0"));
        line_player_0->setGeometry(QRect(760, 520, 91, 51));
        QFont font;
        font.setFamilies({QString::fromUtf8("\345\215\216\346\226\207\350\241\214\346\245\267")});
        font.setPointSize(16);
        line_player_0->setFont(font);
        btn_4_1 = new QPushButton(netpan);
        btn_4_1->setObjectName(QString::fromUtf8("btn_4_1"));
        btn_4_1->setEnabled(true);
        btn_4_1->setGeometry(QRect(320, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_1->sizePolicy().hasHeightForWidth());
        btn_4_1->setSizePolicy(sizePolicy);
        btn_4_1->setMinimumSize(QSize(50, 50));
        btn_4_1->setMaximumSize(QSize(60, 50));
        btn_4_1->setStyleSheet(QString::fromUtf8(""));
        btn_4_1->setFlat(false);
        btn_7_2 = new QPushButton(netpan);
        btn_7_2->setObjectName(QString::fromUtf8("btn_7_2"));
        btn_7_2->setEnabled(true);
        btn_7_2->setGeometry(QRect(370, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_2->sizePolicy().hasHeightForWidth());
        btn_7_2->setSizePolicy(sizePolicy);
        btn_7_2->setMinimumSize(QSize(50, 50));
        btn_7_2->setMaximumSize(QSize(60, 50));
        btn_7_2->setStyleSheet(QString::fromUtf8(""));
        btn_7_2->setFlat(false);
        btn_5_8 = new QPushButton(netpan);
        btn_5_8->setObjectName(QString::fromUtf8("btn_5_8"));
        btn_5_8->setEnabled(true);
        btn_5_8->setGeometry(QRect(670, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_8->sizePolicy().hasHeightForWidth());
        btn_5_8->setSizePolicy(sizePolicy);
        btn_5_8->setMinimumSize(QSize(50, 50));
        btn_5_8->setMaximumSize(QSize(60, 50));
        btn_5_8->setStyleSheet(QString::fromUtf8(""));
        btn_5_8->setFlat(false);
        btn_6_6 = new QPushButton(netpan);
        btn_6_6->setObjectName(QString::fromUtf8("btn_6_6"));
        btn_6_6->setEnabled(true);
        btn_6_6->setGeometry(QRect(570, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_6->sizePolicy().hasHeightForWidth());
        btn_6_6->setSizePolicy(sizePolicy);
        btn_6_6->setMinimumSize(QSize(50, 50));
        btn_6_6->setMaximumSize(QSize(60, 50));
        btn_6_6->setStyleSheet(QString::fromUtf8(""));
        btn_6_6->setFlat(false);
        btn_startgame = new QPushButton(netpan);
        btn_startgame->setObjectName(QString::fromUtf8("btn_startgame"));
        btn_startgame->setGeometry(QRect(790, 260, 91, 61));
        btn_3_3 = new QPushButton(netpan);
        btn_3_3->setObjectName(QString::fromUtf8("btn_3_3"));
        btn_3_3->setEnabled(true);
        btn_3_3->setGeometry(QRect(420, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_3->sizePolicy().hasHeightForWidth());
        btn_3_3->setSizePolicy(sizePolicy);
        btn_3_3->setMinimumSize(QSize(50, 50));
        btn_3_3->setMaximumSize(QSize(60, 50));
        btn_3_3->setStyleSheet(QString::fromUtf8(""));
        btn_3_3->setFlat(false);
        btn_6_5 = new QPushButton(netpan);
        btn_6_5->setObjectName(QString::fromUtf8("btn_6_5"));
        btn_6_5->setEnabled(true);
        btn_6_5->setGeometry(QRect(520, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_5->sizePolicy().hasHeightForWidth());
        btn_6_5->setSizePolicy(sizePolicy);
        btn_6_5->setMinimumSize(QSize(50, 50));
        btn_6_5->setMaximumSize(QSize(60, 50));
        btn_6_5->setStyleSheet(QString::fromUtf8(""));
        btn_6_5->setFlat(false);
        btn_2_7 = new QPushButton(netpan);
        btn_2_7->setObjectName(QString::fromUtf8("btn_2_7"));
        btn_2_7->setEnabled(true);
        btn_2_7->setGeometry(QRect(620, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_7->sizePolicy().hasHeightForWidth());
        btn_2_7->setSizePolicy(sizePolicy);
        btn_2_7->setMinimumSize(QSize(50, 50));
        btn_2_7->setMaximumSize(QSize(60, 50));
        btn_2_7->setStyleSheet(QString::fromUtf8(""));
        btn_2_7->setFlat(false);
        btn_6_4 = new QPushButton(netpan);
        btn_6_4->setObjectName(QString::fromUtf8("btn_6_4"));
        btn_6_4->setEnabled(true);
        btn_6_4->setGeometry(QRect(470, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_4->sizePolicy().hasHeightForWidth());
        btn_6_4->setSizePolicy(sizePolicy);
        btn_6_4->setMinimumSize(QSize(50, 50));
        btn_6_4->setMaximumSize(QSize(60, 50));
        btn_6_4->setStyleSheet(QString::fromUtf8(""));
        btn_6_4->setFlat(false);
        btn_2_5 = new QPushButton(netpan);
        btn_2_5->setObjectName(QString::fromUtf8("btn_2_5"));
        btn_2_5->setEnabled(true);
        btn_2_5->setGeometry(QRect(520, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_5->sizePolicy().hasHeightForWidth());
        btn_2_5->setSizePolicy(sizePolicy);
        btn_2_5->setMinimumSize(QSize(50, 50));
        btn_2_5->setMaximumSize(QSize(60, 50));
        btn_2_5->setStyleSheet(QString::fromUtf8(""));
        btn_2_5->setFlat(false);
        btn_2_1 = new QPushButton(netpan);
        btn_2_1->setObjectName(QString::fromUtf8("btn_2_1"));
        btn_2_1->setEnabled(true);
        btn_2_1->setGeometry(QRect(320, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_1->sizePolicy().hasHeightForWidth());
        btn_2_1->setSizePolicy(sizePolicy);
        btn_2_1->setMinimumSize(QSize(50, 50));
        btn_2_1->setMaximumSize(QSize(60, 50));
        btn_2_1->setStyleSheet(QString::fromUtf8(""));
        btn_2_1->setFlat(false);
        btn_3_0 = new QPushButton(netpan);
        btn_3_0->setObjectName(QString::fromUtf8("btn_3_0"));
        btn_3_0->setEnabled(true);
        btn_3_0->setGeometry(QRect(270, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_0->sizePolicy().hasHeightForWidth());
        btn_3_0->setSizePolicy(sizePolicy);
        btn_3_0->setMinimumSize(QSize(50, 50));
        btn_3_0->setMaximumSize(QSize(60, 50));
        btn_3_0->setStyleSheet(QString::fromUtf8(""));
        btn_3_0->setFlat(false);
        btn_0_1 = new QPushButton(netpan);
        btn_0_1->setObjectName(QString::fromUtf8("btn_0_1"));
        btn_0_1->setEnabled(true);
        btn_0_1->setGeometry(QRect(320, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_1->sizePolicy().hasHeightForWidth());
        btn_0_1->setSizePolicy(sizePolicy);
        btn_0_1->setMinimumSize(QSize(50, 50));
        btn_0_1->setMaximumSize(QSize(60, 50));
        btn_0_1->setStyleSheet(QString::fromUtf8(""));
        btn_0_1->setFlat(false);
        btn_0_3 = new QPushButton(netpan);
        btn_0_3->setObjectName(QString::fromUtf8("btn_0_3"));
        btn_0_3->setEnabled(true);
        btn_0_3->setGeometry(QRect(420, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_3->sizePolicy().hasHeightForWidth());
        btn_0_3->setSizePolicy(sizePolicy);
        btn_0_3->setMinimumSize(QSize(50, 50));
        btn_0_3->setMaximumSize(QSize(60, 50));
        btn_0_3->setStyleSheet(QString::fromUtf8(""));
        btn_0_3->setFlat(false);
        btn_5_1 = new QPushButton(netpan);
        btn_5_1->setObjectName(QString::fromUtf8("btn_5_1"));
        btn_5_1->setEnabled(true);
        btn_5_1->setGeometry(QRect(320, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_1->sizePolicy().hasHeightForWidth());
        btn_5_1->setSizePolicy(sizePolicy);
        btn_5_1->setMinimumSize(QSize(50, 50));
        btn_5_1->setMaximumSize(QSize(60, 50));
        btn_5_1->setStyleSheet(QString::fromUtf8(""));
        btn_5_1->setFlat(false);
        btn_6_1 = new QPushButton(netpan);
        btn_6_1->setObjectName(QString::fromUtf8("btn_6_1"));
        btn_6_1->setEnabled(true);
        btn_6_1->setGeometry(QRect(320, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_1->sizePolicy().hasHeightForWidth());
        btn_6_1->setSizePolicy(sizePolicy);
        btn_6_1->setMinimumSize(QSize(50, 50));
        btn_6_1->setMaximumSize(QSize(60, 50));
        btn_6_1->setStyleSheet(QString::fromUtf8(""));
        btn_6_1->setFlat(false);
        btn_1_5 = new QPushButton(netpan);
        btn_1_5->setObjectName(QString::fromUtf8("btn_1_5"));
        btn_1_5->setEnabled(true);
        btn_1_5->setGeometry(QRect(520, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_5->sizePolicy().hasHeightForWidth());
        btn_1_5->setSizePolicy(sizePolicy);
        btn_1_5->setMinimumSize(QSize(50, 50));
        btn_1_5->setMaximumSize(QSize(60, 50));
        btn_1_5->setStyleSheet(QString::fromUtf8(""));
        btn_1_5->setFlat(false);
        btn_5_4 = new QPushButton(netpan);
        btn_5_4->setObjectName(QString::fromUtf8("btn_5_4"));
        btn_5_4->setEnabled(true);
        btn_5_4->setGeometry(QRect(470, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_4->sizePolicy().hasHeightForWidth());
        btn_5_4->setSizePolicy(sizePolicy);
        btn_5_4->setMinimumSize(QSize(50, 50));
        btn_5_4->setMaximumSize(QSize(60, 50));
        btn_5_4->setStyleSheet(QString::fromUtf8(""));
        btn_5_4->setFlat(false);
        btn_7_8 = new QPushButton(netpan);
        btn_7_8->setObjectName(QString::fromUtf8("btn_7_8"));
        btn_7_8->setEnabled(true);
        btn_7_8->setGeometry(QRect(670, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_8->sizePolicy().hasHeightForWidth());
        btn_7_8->setSizePolicy(sizePolicy);
        btn_7_8->setMinimumSize(QSize(50, 50));
        btn_7_8->setMaximumSize(QSize(60, 50));
        btn_7_8->setStyleSheet(QString::fromUtf8(""));
        btn_7_8->setFlat(false);
        btn_8_7 = new QPushButton(netpan);
        btn_8_7->setObjectName(QString::fromUtf8("btn_8_7"));
        btn_8_7->setEnabled(true);
        btn_8_7->setGeometry(QRect(620, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_7->sizePolicy().hasHeightForWidth());
        btn_8_7->setSizePolicy(sizePolicy);
        btn_8_7->setMinimumSize(QSize(50, 50));
        btn_8_7->setMaximumSize(QSize(60, 50));
        btn_8_7->setStyleSheet(QString::fromUtf8(""));
        btn_8_7->setFlat(false);
        btn_2_4 = new QPushButton(netpan);
        btn_2_4->setObjectName(QString::fromUtf8("btn_2_4"));
        btn_2_4->setEnabled(true);
        btn_2_4->setGeometry(QRect(470, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_4->sizePolicy().hasHeightForWidth());
        btn_2_4->setSizePolicy(sizePolicy);
        btn_2_4->setMinimumSize(QSize(50, 50));
        btn_2_4->setMaximumSize(QSize(60, 50));
        btn_2_4->setStyleSheet(QString::fromUtf8(""));
        btn_2_4->setFlat(false);
        btn_8_1 = new QPushButton(netpan);
        btn_8_1->setObjectName(QString::fromUtf8("btn_8_1"));
        btn_8_1->setEnabled(true);
        btn_8_1->setGeometry(QRect(320, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_1->sizePolicy().hasHeightForWidth());
        btn_8_1->setSizePolicy(sizePolicy);
        btn_8_1->setMinimumSize(QSize(50, 50));
        btn_8_1->setMaximumSize(QSize(60, 50));
        btn_8_1->setStyleSheet(QString::fromUtf8(""));
        btn_8_1->setFlat(false);
        txtl_pan_time = new QLineEdit(netpan);
        txtl_pan_time->setObjectName(QString::fromUtf8("txtl_pan_time"));
        txtl_pan_time->setEnabled(true);
        txtl_pan_time->setGeometry(QRect(830, 150, 131, 81));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Gigi")});
        font1.setPointSize(36);
        font1.setBold(false);
        font1.setItalic(false);
        txtl_pan_time->setFont(font1);
        btn_3_5 = new QPushButton(netpan);
        btn_3_5->setObjectName(QString::fromUtf8("btn_3_5"));
        btn_3_5->setEnabled(true);
        btn_3_5->setGeometry(QRect(520, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_5->sizePolicy().hasHeightForWidth());
        btn_3_5->setSizePolicy(sizePolicy);
        btn_3_5->setMinimumSize(QSize(50, 50));
        btn_3_5->setMaximumSize(QSize(60, 50));
        btn_3_5->setStyleSheet(QString::fromUtf8(""));
        btn_3_5->setFlat(false);
        label = new QLabel(netpan);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(750, 150, 81, 31));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        label->setFont(font2);
        btn_2_0 = new QPushButton(netpan);
        btn_2_0->setObjectName(QString::fromUtf8("btn_2_0"));
        btn_2_0->setEnabled(true);
        btn_2_0->setGeometry(QRect(270, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_0->sizePolicy().hasHeightForWidth());
        btn_2_0->setSizePolicy(sizePolicy);
        btn_2_0->setMinimumSize(QSize(50, 50));
        btn_2_0->setMaximumSize(QSize(60, 50));
        btn_2_0->setStyleSheet(QString::fromUtf8(""));
        btn_2_0->setFlat(false);
        btn_2_2 = new QPushButton(netpan);
        btn_2_2->setObjectName(QString::fromUtf8("btn_2_2"));
        btn_2_2->setEnabled(true);
        btn_2_2->setGeometry(QRect(370, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_2->sizePolicy().hasHeightForWidth());
        btn_2_2->setSizePolicy(sizePolicy);
        btn_2_2->setMinimumSize(QSize(50, 50));
        btn_2_2->setMaximumSize(QSize(60, 50));
        btn_2_2->setStyleSheet(QString::fromUtf8(""));
        btn_2_2->setFlat(false);
        btn_5_0 = new QPushButton(netpan);
        btn_5_0->setObjectName(QString::fromUtf8("btn_5_0"));
        btn_5_0->setEnabled(true);
        btn_5_0->setGeometry(QRect(270, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_0->sizePolicy().hasHeightForWidth());
        btn_5_0->setSizePolicy(sizePolicy);
        btn_5_0->setMinimumSize(QSize(50, 50));
        btn_5_0->setMaximumSize(QSize(60, 50));
        btn_5_0->setStyleSheet(QString::fromUtf8(""));
        btn_5_0->setFlat(false);
        btn_2_8 = new QPushButton(netpan);
        btn_2_8->setObjectName(QString::fromUtf8("btn_2_8"));
        btn_2_8->setEnabled(true);
        btn_2_8->setGeometry(QRect(670, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_8->sizePolicy().hasHeightForWidth());
        btn_2_8->setSizePolicy(sizePolicy);
        btn_2_8->setMinimumSize(QSize(50, 50));
        btn_2_8->setMaximumSize(QSize(60, 50));
        btn_2_8->setStyleSheet(QString::fromUtf8(""));
        btn_2_8->setFlat(false);
        btn_4_6 = new QPushButton(netpan);
        btn_4_6->setObjectName(QString::fromUtf8("btn_4_6"));
        btn_4_6->setEnabled(true);
        btn_4_6->setGeometry(QRect(570, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_6->sizePolicy().hasHeightForWidth());
        btn_4_6->setSizePolicy(sizePolicy);
        btn_4_6->setMinimumSize(QSize(50, 50));
        btn_4_6->setMaximumSize(QSize(60, 50));
        btn_4_6->setStyleSheet(QString::fromUtf8(""));
        btn_4_6->setFlat(false);
        btn_white = new QPushButton(netpan);
        btn_white->setObjectName(QString::fromUtf8("btn_white"));
        btn_white->setEnabled(false);
        btn_white->setGeometry(QRect(970, 450, 50, 50));
        sizePolicy.setHeightForWidth(btn_white->sizePolicy().hasHeightForWidth());
        btn_white->setSizePolicy(sizePolicy);
        btn_white->setMinimumSize(QSize(50, 50));
        btn_white->setMaximumSize(QSize(60, 50));
        btn_white->setStyleSheet(QString::fromUtf8(""));
        btn_white->setFlat(true);
        btn_7_3 = new QPushButton(netpan);
        btn_7_3->setObjectName(QString::fromUtf8("btn_7_3"));
        btn_7_3->setEnabled(true);
        btn_7_3->setGeometry(QRect(420, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_3->sizePolicy().hasHeightForWidth());
        btn_7_3->setSizePolicy(sizePolicy);
        btn_7_3->setMinimumSize(QSize(50, 50));
        btn_7_3->setMaximumSize(QSize(60, 50));
        btn_7_3->setStyleSheet(QString::fromUtf8(""));
        btn_7_3->setFlat(false);
        btn_5_6 = new QPushButton(netpan);
        btn_5_6->setObjectName(QString::fromUtf8("btn_5_6"));
        btn_5_6->setEnabled(true);
        btn_5_6->setGeometry(QRect(570, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_6->sizePolicy().hasHeightForWidth());
        btn_5_6->setSizePolicy(sizePolicy);
        btn_5_6->setMinimumSize(QSize(50, 50));
        btn_5_6->setMaximumSize(QSize(60, 50));
        btn_5_6->setStyleSheet(QString::fromUtf8(""));
        btn_5_6->setFlat(false);
        btn_2_6 = new QPushButton(netpan);
        btn_2_6->setObjectName(QString::fromUtf8("btn_2_6"));
        btn_2_6->setEnabled(true);
        btn_2_6->setGeometry(QRect(570, 240, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_6->sizePolicy().hasHeightForWidth());
        btn_2_6->setSizePolicy(sizePolicy);
        btn_2_6->setMinimumSize(QSize(50, 50));
        btn_2_6->setMaximumSize(QSize(60, 50));
        btn_2_6->setStyleSheet(QString::fromUtf8(""));
        btn_2_6->setFlat(false);
        btn_0_2 = new QPushButton(netpan);
        btn_0_2->setObjectName(QString::fromUtf8("btn_0_2"));
        btn_0_2->setEnabled(true);
        btn_0_2->setGeometry(QRect(370, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_2->sizePolicy().hasHeightForWidth());
        btn_0_2->setSizePolicy(sizePolicy);
        btn_0_2->setMinimumSize(QSize(50, 50));
        btn_0_2->setMaximumSize(QSize(60, 50));
        btn_0_2->setStyleSheet(QString::fromUtf8(""));
        btn_0_2->setFlat(false);
        btn_1_1 = new QPushButton(netpan);
        btn_1_1->setObjectName(QString::fromUtf8("btn_1_1"));
        btn_1_1->setEnabled(true);
        btn_1_1->setGeometry(QRect(320, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_1->sizePolicy().hasHeightForWidth());
        btn_1_1->setSizePolicy(sizePolicy);
        btn_1_1->setMinimumSize(QSize(50, 50));
        btn_1_1->setMaximumSize(QSize(60, 50));
        btn_1_1->setStyleSheet(QString::fromUtf8(""));
        btn_1_1->setFlat(false);
        btn_4_5 = new QPushButton(netpan);
        btn_4_5->setObjectName(QString::fromUtf8("btn_4_5"));
        btn_4_5->setEnabled(true);
        btn_4_5->setGeometry(QRect(520, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_5->sizePolicy().hasHeightForWidth());
        btn_4_5->setSizePolicy(sizePolicy);
        btn_4_5->setMinimumSize(QSize(50, 50));
        btn_4_5->setMaximumSize(QSize(60, 50));
        btn_4_5->setStyleSheet(QString::fromUtf8(""));
        btn_4_5->setFlat(false);
        btn_3_4 = new QPushButton(netpan);
        btn_3_4->setObjectName(QString::fromUtf8("btn_3_4"));
        btn_3_4->setEnabled(true);
        btn_3_4->setGeometry(QRect(470, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_4->sizePolicy().hasHeightForWidth());
        btn_3_4->setSizePolicy(sizePolicy);
        btn_3_4->setMinimumSize(QSize(50, 50));
        btn_3_4->setMaximumSize(QSize(60, 50));
        btn_3_4->setStyleSheet(QString::fromUtf8(""));
        btn_3_4->setFlat(false);
        btn_6_7 = new QPushButton(netpan);
        btn_6_7->setObjectName(QString::fromUtf8("btn_6_7"));
        btn_6_7->setEnabled(true);
        btn_6_7->setGeometry(QRect(620, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_7->sizePolicy().hasHeightForWidth());
        btn_6_7->setSizePolicy(sizePolicy);
        btn_6_7->setMinimumSize(QSize(50, 50));
        btn_6_7->setMaximumSize(QSize(60, 50));
        btn_6_7->setStyleSheet(QString::fromUtf8(""));
        btn_6_7->setFlat(false);
        btn_4_7 = new QPushButton(netpan);
        btn_4_7->setObjectName(QString::fromUtf8("btn_4_7"));
        btn_4_7->setEnabled(true);
        btn_4_7->setGeometry(QRect(620, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_7->sizePolicy().hasHeightForWidth());
        btn_4_7->setSizePolicy(sizePolicy);
        btn_4_7->setMinimumSize(QSize(50, 50));
        btn_4_7->setMaximumSize(QSize(60, 50));
        btn_4_7->setStyleSheet(QString::fromUtf8(""));
        btn_4_7->setFlat(false);
        btn_4_0 = new QPushButton(netpan);
        btn_4_0->setObjectName(QString::fromUtf8("btn_4_0"));
        btn_4_0->setEnabled(true);
        btn_4_0->setGeometry(QRect(270, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_0->sizePolicy().hasHeightForWidth());
        btn_4_0->setSizePolicy(sizePolicy);
        btn_4_0->setMinimumSize(QSize(50, 50));
        btn_4_0->setMaximumSize(QSize(60, 50));
        btn_4_0->setStyleSheet(QString::fromUtf8(""));
        btn_4_0->setFlat(false);
        btn_8_0 = new QPushButton(netpan);
        btn_8_0->setObjectName(QString::fromUtf8("btn_8_0"));
        btn_8_0->setEnabled(true);
        btn_8_0->setGeometry(QRect(270, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_0->sizePolicy().hasHeightForWidth());
        btn_8_0->setSizePolicy(sizePolicy);
        btn_8_0->setMinimumSize(QSize(50, 50));
        btn_8_0->setMaximumSize(QSize(60, 50));
        btn_8_0->setStyleSheet(QString::fromUtf8(""));
        btn_8_0->setFlat(false);
        btn_3_2 = new QPushButton(netpan);
        btn_3_2->setObjectName(QString::fromUtf8("btn_3_2"));
        btn_3_2->setEnabled(true);
        btn_3_2->setGeometry(QRect(370, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_2->sizePolicy().hasHeightForWidth());
        btn_3_2->setSizePolicy(sizePolicy);
        btn_3_2->setMinimumSize(QSize(50, 50));
        btn_3_2->setMaximumSize(QSize(60, 50));
        btn_3_2->setStyleSheet(QString::fromUtf8(""));
        btn_3_2->setFlat(false);
        btn_0_0 = new QPushButton(netpan);
        btn_0_0->setObjectName(QString::fromUtf8("btn_0_0"));
        btn_0_0->setEnabled(true);
        btn_0_0->setGeometry(QRect(270, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_0->sizePolicy().hasHeightForWidth());
        btn_0_0->setSizePolicy(sizePolicy);
        btn_0_0->setMinimumSize(QSize(50, 50));
        btn_0_0->setMaximumSize(QSize(60, 50));
        btn_0_0->setStyleSheet(QString::fromUtf8(""));
        btn_0_0->setFlat(false);
        btn_3_8 = new QPushButton(netpan);
        btn_3_8->setObjectName(QString::fromUtf8("btn_3_8"));
        btn_3_8->setEnabled(true);
        btn_3_8->setGeometry(QRect(670, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_8->sizePolicy().hasHeightForWidth());
        btn_3_8->setSizePolicy(sizePolicy);
        btn_3_8->setMinimumSize(QSize(50, 50));
        btn_3_8->setMaximumSize(QSize(60, 50));
        btn_3_8->setStyleSheet(QString::fromUtf8(""));
        btn_3_8->setFlat(false);
        btn_0_7 = new QPushButton(netpan);
        btn_0_7->setObjectName(QString::fromUtf8("btn_0_7"));
        btn_0_7->setEnabled(true);
        btn_0_7->setGeometry(QRect(620, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_7->sizePolicy().hasHeightForWidth());
        btn_0_7->setSizePolicy(sizePolicy);
        btn_0_7->setMinimumSize(QSize(50, 50));
        btn_0_7->setMaximumSize(QSize(60, 50));
        btn_0_7->setStyleSheet(QString::fromUtf8(""));
        btn_0_7->setFlat(false);
        label_3 = new QLabel(netpan);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(870, 510, 69, 71));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Informal Roman")});
        font3.setPointSize(28);
        label_3->setFont(font3);
        btn_7_1 = new QPushButton(netpan);
        btn_7_1->setObjectName(QString::fromUtf8("btn_7_1"));
        btn_7_1->setEnabled(true);
        btn_7_1->setGeometry(QRect(320, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_1->sizePolicy().hasHeightForWidth());
        btn_7_1->setSizePolicy(sizePolicy);
        btn_7_1->setMinimumSize(QSize(50, 50));
        btn_7_1->setMaximumSize(QSize(60, 50));
        btn_7_1->setStyleSheet(QString::fromUtf8(""));
        btn_7_1->setFlat(false);
        btn_black = new QPushButton(netpan);
        btn_black->setObjectName(QString::fromUtf8("btn_black"));
        btn_black->setEnabled(false);
        btn_black->setGeometry(QRect(780, 450, 50, 50));
        sizePolicy.setHeightForWidth(btn_black->sizePolicy().hasHeightForWidth());
        btn_black->setSizePolicy(sizePolicy);
        btn_black->setMinimumSize(QSize(50, 50));
        btn_black->setMaximumSize(QSize(60, 50));
        btn_black->setStyleSheet(QString::fromUtf8(""));
        btn_black->setFlat(true);
        btn_0_5 = new QPushButton(netpan);
        btn_0_5->setObjectName(QString::fromUtf8("btn_0_5"));
        btn_0_5->setEnabled(true);
        btn_0_5->setGeometry(QRect(520, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_5->sizePolicy().hasHeightForWidth());
        btn_0_5->setSizePolicy(sizePolicy);
        btn_0_5->setMinimumSize(QSize(50, 50));
        btn_0_5->setMaximumSize(QSize(60, 50));
        btn_0_5->setStyleSheet(QString::fromUtf8(""));
        btn_0_5->setFlat(false);
        btn_6_0 = new QPushButton(netpan);
        btn_6_0->setObjectName(QString::fromUtf8("btn_6_0"));
        btn_6_0->setEnabled(true);
        btn_6_0->setGeometry(QRect(270, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_0->sizePolicy().hasHeightForWidth());
        btn_6_0->setSizePolicy(sizePolicy);
        btn_6_0->setMinimumSize(QSize(50, 50));
        btn_6_0->setMaximumSize(QSize(60, 50));
        btn_6_0->setStyleSheet(QString::fromUtf8(""));
        btn_6_0->setFlat(false);
        btn_0_4 = new QPushButton(netpan);
        btn_0_4->setObjectName(QString::fromUtf8("btn_0_4"));
        btn_0_4->setEnabled(true);
        btn_0_4->setGeometry(QRect(470, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_4->sizePolicy().hasHeightForWidth());
        btn_0_4->setSizePolicy(sizePolicy);
        btn_0_4->setMinimumSize(QSize(50, 50));
        btn_0_4->setMaximumSize(QSize(60, 50));
        btn_0_4->setStyleSheet(QString::fromUtf8(""));
        btn_0_4->setFlat(false);
        btn_7_7 = new QPushButton(netpan);
        btn_7_7->setObjectName(QString::fromUtf8("btn_7_7"));
        btn_7_7->setEnabled(true);
        btn_7_7->setGeometry(QRect(620, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_7->sizePolicy().hasHeightForWidth());
        btn_7_7->setSizePolicy(sizePolicy);
        btn_7_7->setMinimumSize(QSize(50, 50));
        btn_7_7->setMaximumSize(QSize(60, 50));
        btn_7_7->setStyleSheet(QString::fromUtf8(""));
        btn_7_7->setFlat(false);
        btn_4_2 = new QPushButton(netpan);
        btn_4_2->setObjectName(QString::fromUtf8("btn_4_2"));
        btn_4_2->setEnabled(true);
        btn_4_2->setGeometry(QRect(370, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_2->sizePolicy().hasHeightForWidth());
        btn_4_2->setSizePolicy(sizePolicy);
        btn_4_2->setMinimumSize(QSize(50, 50));
        btn_4_2->setMaximumSize(QSize(60, 50));
        btn_4_2->setStyleSheet(QString::fromUtf8(""));
        btn_4_2->setFlat(false);
        btn_6_3 = new QPushButton(netpan);
        btn_6_3->setObjectName(QString::fromUtf8("btn_6_3"));
        btn_6_3->setEnabled(true);
        btn_6_3->setGeometry(QRect(420, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_3->sizePolicy().hasHeightForWidth());
        btn_6_3->setSizePolicy(sizePolicy);
        btn_6_3->setMinimumSize(QSize(50, 50));
        btn_6_3->setMaximumSize(QSize(60, 50));
        btn_6_3->setStyleSheet(QString::fromUtf8(""));
        btn_6_3->setFlat(false);
        btn_5_7 = new QPushButton(netpan);
        btn_5_7->setObjectName(QString::fromUtf8("btn_5_7"));
        btn_5_7->setEnabled(true);
        btn_5_7->setGeometry(QRect(620, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_7->sizePolicy().hasHeightForWidth());
        btn_5_7->setSizePolicy(sizePolicy);
        btn_5_7->setMinimumSize(QSize(50, 50));
        btn_5_7->setMaximumSize(QSize(60, 50));
        btn_5_7->setStyleSheet(QString::fromUtf8(""));
        btn_5_7->setFlat(false);
        btn_7_0 = new QPushButton(netpan);
        btn_7_0->setObjectName(QString::fromUtf8("btn_7_0"));
        btn_7_0->setEnabled(true);
        btn_7_0->setGeometry(QRect(270, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_0->sizePolicy().hasHeightForWidth());
        btn_7_0->setSizePolicy(sizePolicy);
        btn_7_0->setMinimumSize(QSize(50, 50));
        btn_7_0->setMaximumSize(QSize(60, 50));
        btn_7_0->setStyleSheet(QString::fromUtf8(""));
        btn_7_0->setFlat(false);
        btn_6_8 = new QPushButton(netpan);
        btn_6_8->setObjectName(QString::fromUtf8("btn_6_8"));
        btn_6_8->setEnabled(true);
        btn_6_8->setGeometry(QRect(670, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_8->sizePolicy().hasHeightForWidth());
        btn_6_8->setSizePolicy(sizePolicy);
        btn_6_8->setMinimumSize(QSize(50, 50));
        btn_6_8->setMaximumSize(QSize(60, 50));
        btn_6_8->setStyleSheet(QString::fromUtf8(""));
        btn_6_8->setFlat(false);
        btn_4_4 = new QPushButton(netpan);
        btn_4_4->setObjectName(QString::fromUtf8("btn_4_4"));
        btn_4_4->setEnabled(true);
        btn_4_4->setGeometry(QRect(470, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_4->sizePolicy().hasHeightForWidth());
        btn_4_4->setSizePolicy(sizePolicy);
        btn_4_4->setMinimumSize(QSize(50, 50));
        btn_4_4->setMaximumSize(QSize(60, 50));
        btn_4_4->setStyleSheet(QString::fromUtf8(""));
        btn_4_4->setFlat(false);
        btn_4_3 = new QPushButton(netpan);
        btn_4_3->setObjectName(QString::fromUtf8("btn_4_3"));
        btn_4_3->setEnabled(true);
        btn_4_3->setGeometry(QRect(420, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_3->sizePolicy().hasHeightForWidth());
        btn_4_3->setSizePolicy(sizePolicy);
        btn_4_3->setMinimumSize(QSize(50, 50));
        btn_4_3->setMaximumSize(QSize(60, 50));
        btn_4_3->setStyleSheet(QString::fromUtf8(""));
        btn_4_3->setFlat(false);
        btn_8_6 = new QPushButton(netpan);
        btn_8_6->setObjectName(QString::fromUtf8("btn_8_6"));
        btn_8_6->setEnabled(true);
        btn_8_6->setGeometry(QRect(570, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_6->sizePolicy().hasHeightForWidth());
        btn_8_6->setSizePolicy(sizePolicy);
        btn_8_6->setMinimumSize(QSize(50, 50));
        btn_8_6->setMaximumSize(QSize(60, 50));
        btn_8_6->setStyleSheet(QString::fromUtf8(""));
        btn_8_6->setFlat(false);
        btn_6_2 = new QPushButton(netpan);
        btn_6_2->setObjectName(QString::fromUtf8("btn_6_2"));
        btn_6_2->setEnabled(true);
        btn_6_2->setGeometry(QRect(370, 440, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_2->sizePolicy().hasHeightForWidth());
        btn_6_2->setSizePolicy(sizePolicy);
        btn_6_2->setMinimumSize(QSize(50, 50));
        btn_6_2->setMaximumSize(QSize(60, 50));
        btn_6_2->setStyleSheet(QString::fromUtf8(""));
        btn_6_2->setFlat(false);
        btn_7_6 = new QPushButton(netpan);
        btn_7_6->setObjectName(QString::fromUtf8("btn_7_6"));
        btn_7_6->setEnabled(true);
        btn_7_6->setGeometry(QRect(570, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_6->sizePolicy().hasHeightForWidth());
        btn_7_6->setSizePolicy(sizePolicy);
        btn_7_6->setMinimumSize(QSize(50, 50));
        btn_7_6->setMaximumSize(QSize(60, 50));
        btn_7_6->setStyleSheet(QString::fromUtf8(""));
        btn_7_6->setFlat(false);
        btn_stop = new QPushButton(netpan);
        btn_stop->setObjectName(QString::fromUtf8("btn_stop"));
        btn_stop->setGeometry(QRect(900, 260, 91, 61));
        back = new QPushButton(netpan);
        back->setObjectName(QString::fromUtf8("back"));
        back->setGeometry(QRect(1090, 10, 51, 51));
        QFont font4;
        font4.setBold(true);
        back->setFont(font4);
        btn_3_7 = new QPushButton(netpan);
        btn_3_7->setObjectName(QString::fromUtf8("btn_3_7"));
        btn_3_7->setEnabled(true);
        btn_3_7->setGeometry(QRect(620, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_7->sizePolicy().hasHeightForWidth());
        btn_3_7->setSizePolicy(sizePolicy);
        btn_3_7->setMinimumSize(QSize(50, 50));
        btn_3_7->setMaximumSize(QSize(60, 50));
        btn_3_7->setStyleSheet(QString::fromUtf8(""));
        btn_3_7->setFlat(false);
        btn_8_2 = new QPushButton(netpan);
        btn_8_2->setObjectName(QString::fromUtf8("btn_8_2"));
        btn_8_2->setEnabled(true);
        btn_8_2->setGeometry(QRect(370, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_2->sizePolicy().hasHeightForWidth());
        btn_8_2->setSizePolicy(sizePolicy);
        btn_8_2->setMinimumSize(QSize(50, 50));
        btn_8_2->setMaximumSize(QSize(60, 50));
        btn_8_2->setStyleSheet(QString::fromUtf8(""));
        btn_8_2->setFlat(false);
        btn_1_8 = new QPushButton(netpan);
        btn_1_8->setObjectName(QString::fromUtf8("btn_1_8"));
        btn_1_8->setEnabled(true);
        btn_1_8->setGeometry(QRect(670, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_8->sizePolicy().hasHeightForWidth());
        btn_1_8->setSizePolicy(sizePolicy);
        btn_1_8->setMinimumSize(QSize(50, 50));
        btn_1_8->setMaximumSize(QSize(60, 50));
        btn_1_8->setStyleSheet(QString::fromUtf8(""));
        btn_1_8->setFlat(false);
        btn_5_2 = new QPushButton(netpan);
        btn_5_2->setObjectName(QString::fromUtf8("btn_5_2"));
        btn_5_2->setEnabled(true);
        btn_5_2->setGeometry(QRect(370, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_2->sizePolicy().hasHeightForWidth());
        btn_5_2->setSizePolicy(sizePolicy);
        btn_5_2->setMinimumSize(QSize(50, 50));
        btn_5_2->setMaximumSize(QSize(60, 50));
        btn_5_2->setStyleSheet(QString::fromUtf8(""));
        btn_5_2->setFlat(false);
        line_player_1 = new QLineEdit(netpan);
        line_player_1->setObjectName(QString::fromUtf8("line_player_1"));
        line_player_1->setGeometry(QRect(950, 520, 91, 51));
        line_player_1->setFont(font);
        btn_0_8 = new QPushButton(netpan);
        btn_0_8->setObjectName(QString::fromUtf8("btn_0_8"));
        btn_0_8->setEnabled(true);
        btn_0_8->setGeometry(QRect(670, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_8->sizePolicy().hasHeightForWidth());
        btn_0_8->setSizePolicy(sizePolicy);
        btn_0_8->setMinimumSize(QSize(50, 50));
        btn_0_8->setMaximumSize(QSize(60, 50));
        btn_0_8->setStyleSheet(QString::fromUtf8(""));
        btn_0_8->setFlat(false);
        btn_7_4 = new QPushButton(netpan);
        btn_7_4->setObjectName(QString::fromUtf8("btn_7_4"));
        btn_7_4->setEnabled(true);
        btn_7_4->setGeometry(QRect(470, 490, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_4->sizePolicy().hasHeightForWidth());
        btn_7_4->setSizePolicy(sizePolicy);
        btn_7_4->setMinimumSize(QSize(50, 50));
        btn_7_4->setMaximumSize(QSize(60, 50));
        btn_7_4->setStyleSheet(QString::fromUtf8(""));
        btn_7_4->setFlat(false);
        btn_4_8 = new QPushButton(netpan);
        btn_4_8->setObjectName(QString::fromUtf8("btn_4_8"));
        btn_4_8->setEnabled(true);
        btn_4_8->setGeometry(QRect(670, 340, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_8->sizePolicy().hasHeightForWidth());
        btn_4_8->setSizePolicy(sizePolicy);
        btn_4_8->setMinimumSize(QSize(50, 50));
        btn_4_8->setMaximumSize(QSize(60, 50));
        btn_4_8->setStyleSheet(QString::fromUtf8(""));
        btn_4_8->setFlat(false);
        btn_0_6 = new QPushButton(netpan);
        btn_0_6->setObjectName(QString::fromUtf8("btn_0_6"));
        btn_0_6->setEnabled(true);
        btn_0_6->setGeometry(QRect(570, 140, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_6->sizePolicy().hasHeightForWidth());
        btn_0_6->setSizePolicy(sizePolicy);
        btn_0_6->setMinimumSize(QSize(50, 50));
        btn_0_6->setMaximumSize(QSize(60, 50));
        btn_0_6->setStyleSheet(QString::fromUtf8(""));
        btn_0_6->setFlat(false);
        btn_1_3 = new QPushButton(netpan);
        btn_1_3->setObjectName(QString::fromUtf8("btn_1_3"));
        btn_1_3->setEnabled(true);
        btn_1_3->setGeometry(QRect(420, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_3->sizePolicy().hasHeightForWidth());
        btn_1_3->setSizePolicy(sizePolicy);
        btn_1_3->setMinimumSize(QSize(50, 50));
        btn_1_3->setMaximumSize(QSize(60, 50));
        btn_1_3->setStyleSheet(QString::fromUtf8(""));
        btn_1_3->setFlat(false);
        btn_3_1 = new QPushButton(netpan);
        btn_3_1->setObjectName(QString::fromUtf8("btn_3_1"));
        btn_3_1->setEnabled(true);
        btn_3_1->setGeometry(QRect(320, 290, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_1->sizePolicy().hasHeightForWidth());
        btn_3_1->setSizePolicy(sizePolicy);
        btn_3_1->setMinimumSize(QSize(50, 50));
        btn_3_1->setMaximumSize(QSize(60, 50));
        btn_3_1->setStyleSheet(QString::fromUtf8(""));
        btn_3_1->setFlat(false);
        btn_5_3 = new QPushButton(netpan);
        btn_5_3->setObjectName(QString::fromUtf8("btn_5_3"));
        btn_5_3->setEnabled(true);
        btn_5_3->setGeometry(QRect(420, 390, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_3->sizePolicy().hasHeightForWidth());
        btn_5_3->setSizePolicy(sizePolicy);
        btn_5_3->setMinimumSize(QSize(50, 50));
        btn_5_3->setMaximumSize(QSize(60, 50));
        btn_5_3->setStyleSheet(QString::fromUtf8(""));
        btn_5_3->setFlat(false);
        btn_1_4 = new QPushButton(netpan);
        btn_1_4->setObjectName(QString::fromUtf8("btn_1_4"));
        btn_1_4->setEnabled(true);
        btn_1_4->setGeometry(QRect(470, 190, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_4->sizePolicy().hasHeightForWidth());
        btn_1_4->setSizePolicy(sizePolicy);
        btn_1_4->setMinimumSize(QSize(50, 50));
        btn_1_4->setMaximumSize(QSize(60, 50));
        btn_1_4->setStyleSheet(QString::fromUtf8(""));
        btn_1_4->setFlat(false);
        btn_8_4 = new QPushButton(netpan);
        btn_8_4->setObjectName(QString::fromUtf8("btn_8_4"));
        btn_8_4->setEnabled(true);
        btn_8_4->setGeometry(QRect(470, 540, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_4->sizePolicy().hasHeightForWidth());
        btn_8_4->setSizePolicy(sizePolicy);
        btn_8_4->setMinimumSize(QSize(50, 50));
        btn_8_4->setMaximumSize(QSize(60, 50));
        btn_8_4->setStyleSheet(QString::fromUtf8(""));
        btn_8_4->setFlat(false);
        sendbtn = new QPushButton(netpan);
        sendbtn->setObjectName(QString::fromUtf8("sendbtn"));
        sendbtn->setGeometry(QRect(200, 550, 61, 51));
        Chatline = new QLineEdit(netpan);
        Chatline->setObjectName(QString::fromUtf8("Chatline"));
        Chatline->setGeometry(QRect(20, 560, 171, 31));
        Chatplain = new QPlainTextEdit(netpan);
        Chatplain->setObjectName(QString::fromUtf8("Chatplain"));
        Chatplain->setGeometry(QRect(20, 140, 231, 401));
        PORTEdit = new QLineEdit(netpan);
        PORTEdit->setObjectName(QString::fromUtf8("PORTEdit"));
        PORTEdit->setGeometry(QRect(260, 10, 151, 31));
        reSetButton = new QPushButton(netpan);
        reSetButton->setObjectName(QString::fromUtf8("reSetButton"));
        reSetButton->setGeometry(QRect(420, 0, 81, 41));
        label_2 = new QLabel(netpan);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 10, 69, 20));
        QFont font5;
        font5.setPointSize(11);
        font5.setBold(true);
        label_2->setFont(font5);
        label_4 = new QLabel(netpan);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(200, 10, 69, 20));
        label_4->setFont(font5);
        reStartButton = new QPushButton(netpan);
        reStartButton->setObjectName(QString::fromUtf8("reStartButton"));
        reStartButton->setGeometry(QRect(300, 60, 121, 41));
        connectLabel = new QLabel(netpan);
        connectLabel->setObjectName(QString::fromUtf8("connectLabel"));
        connectLabel->setGeometry(QRect(40, 60, 131, 41));
        connectLabel->setAlignment(Qt::AlignCenter);
        reConnectButton = new QPushButton(netpan);
        reConnectButton->setObjectName(QString::fromUtf8("reConnectButton"));
        reConnectButton->setGeometry(QRect(179, 60, 111, 41));
        IPEdit = new QLineEdit(netpan);
        IPEdit->setObjectName(QString::fromUtf8("IPEdit"));
        IPEdit->setGeometry(QRect(40, 10, 151, 31));
        widget = new QWidget(netpan);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(560, 600, 611, 28));
        horizontalLayout = new QHBoxLayout(widget);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        label_5 = new QLabel(widget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        QFont font6;
        font6.setPointSize(10);
        font6.setBold(true);
        label_5->setFont(font6);

        horizontalLayout->addWidget(label_5);

        choseb = new QRadioButton(widget);
        choseb->setObjectName(QString::fromUtf8("choseb"));
        choseb->setFont(font6);

        horizontalLayout->addWidget(choseb);

        chosew = new QRadioButton(widget);
        chosew->setObjectName(QString::fromUtf8("chosew"));
        chosew->setFont(font6);

        horizontalLayout->addWidget(chosew);


        retranslateUi(netpan);

        QMetaObject::connectSlotsByName(netpan);
    } // setupUi

    void retranslateUi(QWidget *netpan)
    {
        netpan->setWindowTitle(QCoreApplication::translate("netpan", "Form", nullptr));
        btn_1_6->setText(QString());
        btn_2_3->setText(QString());
        btn_7_5->setText(QString());
        btn_1_7->setText(QString());
        btn_5_5->setText(QString());
        btn_3_6->setText(QString());
        btn_1_0->setText(QString());
        btn_8_8->setText(QString());
        btn_8_3->setText(QString());
        btn_1_2->setText(QString());
        btn_8_5->setText(QString());
        btn_lose->setText(QCoreApplication::translate("netpan", "\350\256\244\350\276\223", nullptr));
        line_player_0->setText(QCoreApplication::translate("netpan", "\344\270\201\347\234\237", nullptr));
        btn_4_1->setText(QString());
        btn_7_2->setText(QString());
        btn_5_8->setText(QString());
        btn_6_6->setText(QString());
        btn_startgame->setText(QCoreApplication::translate("netpan", "\345\274\200\345\247\213\346\270\270\346\210\217", nullptr));
        btn_3_3->setText(QString());
        btn_6_5->setText(QString());
        btn_2_7->setText(QString());
        btn_6_4->setText(QString());
        btn_2_5->setText(QString());
        btn_2_1->setText(QString());
        btn_3_0->setText(QString());
        btn_0_1->setText(QString());
        btn_0_3->setText(QString());
        btn_5_1->setText(QString());
        btn_6_1->setText(QString());
        btn_1_5->setText(QString());
        btn_5_4->setText(QString());
        btn_7_8->setText(QString());
        btn_8_7->setText(QString());
        btn_2_4->setText(QString());
        btn_8_1->setText(QString());
        txtl_pan_time->setText(QString());
        btn_3_5->setText(QString());
        label->setText(QCoreApplication::translate("netpan", "\345\200\222\350\256\241\346\227\266\357\274\232", nullptr));
        btn_2_0->setText(QString());
        btn_2_2->setText(QString());
        btn_5_0->setText(QString());
        btn_2_8->setText(QString());
        btn_4_6->setText(QString());
        btn_white->setText(QString());
        btn_7_3->setText(QString());
        btn_5_6->setText(QString());
        btn_2_6->setText(QString());
        btn_0_2->setText(QString());
        btn_1_1->setText(QString());
        btn_4_5->setText(QString());
        btn_3_4->setText(QString());
        btn_6_7->setText(QString());
        btn_4_7->setText(QString());
        btn_4_0->setText(QString());
        btn_8_0->setText(QString());
        btn_3_2->setText(QString());
        btn_0_0->setText(QString());
        btn_3_8->setText(QString());
        btn_0_7->setText(QString());
        label_3->setText(QCoreApplication::translate("netpan", "VS", nullptr));
        btn_7_1->setText(QString());
        btn_black->setText(QString());
        btn_0_5->setText(QString());
        btn_6_0->setText(QString());
        btn_0_4->setText(QString());
        btn_7_7->setText(QString());
        btn_4_2->setText(QString());
        btn_6_3->setText(QString());
        btn_5_7->setText(QString());
        btn_7_0->setText(QString());
        btn_6_8->setText(QString());
        btn_4_4->setText(QString());
        btn_4_3->setText(QString());
        btn_8_6->setText(QString());
        btn_6_2->setText(QString());
        btn_7_6->setText(QString());
        btn_stop->setText(QCoreApplication::translate("netpan", "\346\232\202\345\201\234\346\270\270\346\210\217", nullptr));
        back->setText(QCoreApplication::translate("netpan", "\345\220\216\351\200\200", nullptr));
        btn_3_7->setText(QString());
        btn_8_2->setText(QString());
        btn_1_8->setText(QString());
        btn_5_2->setText(QString());
        line_player_1->setText(QCoreApplication::translate("netpan", "\350\260\267\347\210\261\345\207\214", nullptr));
        btn_0_8->setText(QString());
        btn_7_4->setText(QString());
        btn_4_8->setText(QString());
        btn_0_6->setText(QString());
        btn_1_3->setText(QString());
        btn_3_1->setText(QString());
        btn_5_3->setText(QString());
        btn_1_4->setText(QString());
        btn_8_4->setText(QString());
        sendbtn->setText(QCoreApplication::translate("netpan", "\345\217\221\351\200\201", nullptr));
        reSetButton->setText(QCoreApplication::translate("netpan", "\351\207\215\350\256\276", nullptr));
        label_2->setText(QCoreApplication::translate("netpan", "IP\357\274\232", nullptr));
        label_4->setText(QCoreApplication::translate("netpan", "PORT\357\274\232", nullptr));
        reStartButton->setText(QCoreApplication::translate("netpan", "\346\216\245\345\217\227\351\202\200\350\257\267", nullptr));
        connectLabel->setText(QCoreApplication::translate("netpan", "Connection fail", nullptr));
        reConnectButton->setText(QCoreApplication::translate("netpan", "\345\217\221\351\200\201\351\202\200\350\257\267", nullptr));
        label_5->setText(QCoreApplication::translate("netpan", "\350\257\267\351\200\211\346\213\251\344\275\240\347\232\204\347\224\250\346\210\267\345\220\215\345\222\214\351\242\234\350\211\262\357\274\232", nullptr));
        choseb->setText(QCoreApplication::translate("netpan", "\351\273\221", nullptr));
        chosew->setText(QCoreApplication::translate("netpan", "\347\231\275", nullptr));
    } // retranslateUi

};

namespace Ui {
    class netpan: public Ui_netpan {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NETPAN_H
