/********************************************************************************
** Form generated from reading UI file 'netpan.ui'
**
** Created by: Qt User Interface Compiler version 6.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NETPAN_H
#define UI_NETPAN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_netpan
{
public:
    QPushButton *btn_1_6;
    QPushButton *btn_2_3;
    QPushButton *btn_7_5;
    QPushButton *btn_1_7;
    QPushButton *btn_5_5;
    QPushButton *btn_3_6;
    QPushButton *btn_1_0;
    QPushButton *btn_8_8;
    QPushButton *btn_8_3;
    QPushButton *btn_1_2;
    QPushButton *btn_8_5;
    QPushButton *btn_lose;
    QLineEdit *line_player_0;
    QPushButton *btn_4_1;
    QPushButton *btn_7_2;
    QPushButton *btn_5_8;
    QPushButton *btn_6_6;
    QPushButton *btn_startgame;
    QPushButton *btn_3_3;
    QPushButton *btn_6_5;
    QPushButton *btn_2_7;
    QPushButton *btn_6_4;
    QPushButton *btn_2_5;
    QPushButton *btn_2_1;
    QPushButton *btn_3_0;
    QPushButton *btn_0_1;
    QPushButton *btn_0_3;
    QPushButton *btn_5_1;
    QPushButton *btn_6_1;
    QPushButton *btn_1_5;
    QPushButton *btn_5_4;
    QPushButton *btn_7_8;
    QPushButton *btn_8_7;
    QPushButton *btn_2_4;
    QPushButton *btn_8_1;
    QLineEdit *txtl_pan_time;
    QPushButton *btn_3_5;
    QLabel *label;
    QPushButton *btn_2_0;
    QPushButton *btn_2_2;
    QPushButton *btn_5_0;
    QPushButton *btn_2_8;
    QPushButton *btn_4_6;
    QPushButton *btn_white;
    QPushButton *btn_7_3;
    QPushButton *btn_5_6;
    QPushButton *btn_restart;
    QPushButton *btn_2_6;
    QPushButton *btn_0_2;
    QPushButton *btn_1_1;
    QPushButton *btn_4_5;
    QPushButton *btn_3_4;
    QPushButton *btn_6_7;
    QPushButton *btn_4_7;
    QPushButton *btn_4_0;
    QPushButton *btn_8_0;
    QPushButton *btn_3_2;
    QPushButton *btn_0_0;
    QPushButton *btn_3_8;
    QPushButton *btn_0_7;
    QLabel *label_3;
    QPushButton *btn_7_1;
    QPushButton *btn_black;
    QPushButton *btn_0_5;
    QPushButton *btn_6_0;
    QPushButton *btn_0_4;
    QPushButton *btn_7_7;
    QPushButton *btn_4_2;
    QPushButton *btn_6_3;
    QPushButton *btn_5_7;
    QPushButton *btn_7_0;
    QPushButton *btn_6_8;
    QPushButton *btn_4_4;
    QPushButton *btn_4_3;
    QPushButton *btn_8_6;
    QPushButton *btn_6_2;
    QPushButton *btn_7_6;
    QPushButton *btn_stop;
    QPushButton *back;
    QPushButton *btn_3_7;
    QPushButton *btn_8_2;
    QPushButton *btn_1_8;
    QPushButton *btn_5_2;
    QLineEdit *line_player_1;
    QPushButton *btn_0_8;
    QPushButton *btn_7_4;
    QPushButton *btn_4_8;
    QPushButton *btn_0_6;
    QPushButton *btn_1_3;
    QPushButton *btn_3_1;
    QPushButton *btn_5_3;
    QPushButton *btn_1_4;
    QPushButton *btn_8_4;

    void setupUi(QWidget *netpan)
    {
        if (netpan->objectName().isEmpty())
            netpan->setObjectName(QString::fromUtf8("netpan"));
        netpan->resize(1200, 720);
        btn_1_6 = new QPushButton(netpan);
        btn_1_6->setObjectName(QString::fromUtf8("btn_1_6"));
        btn_1_6->setEnabled(true);
        btn_1_6->setGeometry(QRect(430, 180, 50, 50));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btn_1_6->sizePolicy().hasHeightForWidth());
        btn_1_6->setSizePolicy(sizePolicy);
        btn_1_6->setMinimumSize(QSize(50, 50));
        btn_1_6->setMaximumSize(QSize(60, 50));
        btn_1_6->setStyleSheet(QString::fromUtf8(""));
        btn_1_6->setFlat(true);
        btn_2_3 = new QPushButton(netpan);
        btn_2_3->setObjectName(QString::fromUtf8("btn_2_3"));
        btn_2_3->setEnabled(true);
        btn_2_3->setGeometry(QRect(280, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_3->sizePolicy().hasHeightForWidth());
        btn_2_3->setSizePolicy(sizePolicy);
        btn_2_3->setMinimumSize(QSize(50, 50));
        btn_2_3->setMaximumSize(QSize(60, 50));
        btn_2_3->setStyleSheet(QString::fromUtf8(""));
        btn_2_3->setFlat(true);
        btn_7_5 = new QPushButton(netpan);
        btn_7_5->setObjectName(QString::fromUtf8("btn_7_5"));
        btn_7_5->setEnabled(true);
        btn_7_5->setGeometry(QRect(380, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_5->sizePolicy().hasHeightForWidth());
        btn_7_5->setSizePolicy(sizePolicy);
        btn_7_5->setMinimumSize(QSize(50, 50));
        btn_7_5->setMaximumSize(QSize(60, 50));
        btn_7_5->setStyleSheet(QString::fromUtf8(""));
        btn_7_5->setFlat(true);
        btn_1_7 = new QPushButton(netpan);
        btn_1_7->setObjectName(QString::fromUtf8("btn_1_7"));
        btn_1_7->setEnabled(true);
        btn_1_7->setGeometry(QRect(480, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_7->sizePolicy().hasHeightForWidth());
        btn_1_7->setSizePolicy(sizePolicy);
        btn_1_7->setMinimumSize(QSize(50, 50));
        btn_1_7->setMaximumSize(QSize(60, 50));
        btn_1_7->setStyleSheet(QString::fromUtf8(""));
        btn_1_7->setFlat(true);
        btn_5_5 = new QPushButton(netpan);
        btn_5_5->setObjectName(QString::fromUtf8("btn_5_5"));
        btn_5_5->setEnabled(true);
        btn_5_5->setGeometry(QRect(380, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_5->sizePolicy().hasHeightForWidth());
        btn_5_5->setSizePolicy(sizePolicy);
        btn_5_5->setMinimumSize(QSize(50, 50));
        btn_5_5->setMaximumSize(QSize(60, 50));
        btn_5_5->setStyleSheet(QString::fromUtf8(""));
        btn_5_5->setFlat(true);
        btn_3_6 = new QPushButton(netpan);
        btn_3_6->setObjectName(QString::fromUtf8("btn_3_6"));
        btn_3_6->setEnabled(true);
        btn_3_6->setGeometry(QRect(430, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_6->sizePolicy().hasHeightForWidth());
        btn_3_6->setSizePolicy(sizePolicy);
        btn_3_6->setMinimumSize(QSize(50, 50));
        btn_3_6->setMaximumSize(QSize(60, 50));
        btn_3_6->setStyleSheet(QString::fromUtf8(""));
        btn_3_6->setFlat(true);
        btn_1_0 = new QPushButton(netpan);
        btn_1_0->setObjectName(QString::fromUtf8("btn_1_0"));
        btn_1_0->setEnabled(true);
        btn_1_0->setGeometry(QRect(130, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_0->sizePolicy().hasHeightForWidth());
        btn_1_0->setSizePolicy(sizePolicy);
        btn_1_0->setMinimumSize(QSize(50, 50));
        btn_1_0->setMaximumSize(QSize(60, 50));
        btn_1_0->setStyleSheet(QString::fromUtf8(""));
        btn_1_0->setFlat(true);
        btn_8_8 = new QPushButton(netpan);
        btn_8_8->setObjectName(QString::fromUtf8("btn_8_8"));
        btn_8_8->setEnabled(true);
        btn_8_8->setGeometry(QRect(530, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_8->sizePolicy().hasHeightForWidth());
        btn_8_8->setSizePolicy(sizePolicy);
        btn_8_8->setMinimumSize(QSize(50, 50));
        btn_8_8->setMaximumSize(QSize(50, 50));
        btn_8_8->setStyleSheet(QString::fromUtf8(""));
        btn_8_8->setFlat(true);
        btn_8_3 = new QPushButton(netpan);
        btn_8_3->setObjectName(QString::fromUtf8("btn_8_3"));
        btn_8_3->setEnabled(true);
        btn_8_3->setGeometry(QRect(280, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_3->sizePolicy().hasHeightForWidth());
        btn_8_3->setSizePolicy(sizePolicy);
        btn_8_3->setMinimumSize(QSize(50, 50));
        btn_8_3->setMaximumSize(QSize(60, 50));
        btn_8_3->setStyleSheet(QString::fromUtf8(""));
        btn_8_3->setFlat(true);
        btn_1_2 = new QPushButton(netpan);
        btn_1_2->setObjectName(QString::fromUtf8("btn_1_2"));
        btn_1_2->setEnabled(true);
        btn_1_2->setGeometry(QRect(230, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_2->sizePolicy().hasHeightForWidth());
        btn_1_2->setSizePolicy(sizePolicy);
        btn_1_2->setMinimumSize(QSize(50, 50));
        btn_1_2->setMaximumSize(QSize(60, 50));
        btn_1_2->setStyleSheet(QString::fromUtf8(""));
        btn_1_2->setFlat(true);
        btn_8_5 = new QPushButton(netpan);
        btn_8_5->setObjectName(QString::fromUtf8("btn_8_5"));
        btn_8_5->setEnabled(true);
        btn_8_5->setGeometry(QRect(380, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_5->sizePolicy().hasHeightForWidth());
        btn_8_5->setSizePolicy(sizePolicy);
        btn_8_5->setMinimumSize(QSize(50, 50));
        btn_8_5->setMaximumSize(QSize(60, 50));
        btn_8_5->setStyleSheet(QString::fromUtf8(""));
        btn_8_5->setFlat(true);
        btn_lose = new QPushButton(netpan);
        btn_lose->setObjectName(QString::fromUtf8("btn_lose"));
        btn_lose->setGeometry(QRect(790, 330, 91, 61));
        line_player_0 = new QLineEdit(netpan);
        line_player_0->setObjectName(QString::fromUtf8("line_player_0"));
        line_player_0->setGeometry(QRect(760, 520, 91, 51));
        QFont font;
        font.setFamilies({QString::fromUtf8("\345\215\216\346\226\207\350\241\214\346\245\267")});
        font.setPointSize(16);
        line_player_0->setFont(font);
        btn_4_1 = new QPushButton(netpan);
        btn_4_1->setObjectName(QString::fromUtf8("btn_4_1"));
        btn_4_1->setEnabled(true);
        btn_4_1->setGeometry(QRect(180, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_1->sizePolicy().hasHeightForWidth());
        btn_4_1->setSizePolicy(sizePolicy);
        btn_4_1->setMinimumSize(QSize(50, 50));
        btn_4_1->setMaximumSize(QSize(60, 50));
        btn_4_1->setStyleSheet(QString::fromUtf8(""));
        btn_4_1->setFlat(true);
        btn_7_2 = new QPushButton(netpan);
        btn_7_2->setObjectName(QString::fromUtf8("btn_7_2"));
        btn_7_2->setEnabled(true);
        btn_7_2->setGeometry(QRect(230, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_2->sizePolicy().hasHeightForWidth());
        btn_7_2->setSizePolicy(sizePolicy);
        btn_7_2->setMinimumSize(QSize(50, 50));
        btn_7_2->setMaximumSize(QSize(60, 50));
        btn_7_2->setStyleSheet(QString::fromUtf8(""));
        btn_7_2->setFlat(true);
        btn_5_8 = new QPushButton(netpan);
        btn_5_8->setObjectName(QString::fromUtf8("btn_5_8"));
        btn_5_8->setEnabled(true);
        btn_5_8->setGeometry(QRect(530, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_8->sizePolicy().hasHeightForWidth());
        btn_5_8->setSizePolicy(sizePolicy);
        btn_5_8->setMinimumSize(QSize(50, 50));
        btn_5_8->setMaximumSize(QSize(60, 50));
        btn_5_8->setStyleSheet(QString::fromUtf8(""));
        btn_5_8->setFlat(true);
        btn_6_6 = new QPushButton(netpan);
        btn_6_6->setObjectName(QString::fromUtf8("btn_6_6"));
        btn_6_6->setEnabled(true);
        btn_6_6->setGeometry(QRect(430, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_6->sizePolicy().hasHeightForWidth());
        btn_6_6->setSizePolicy(sizePolicy);
        btn_6_6->setMinimumSize(QSize(50, 50));
        btn_6_6->setMaximumSize(QSize(60, 50));
        btn_6_6->setStyleSheet(QString::fromUtf8(""));
        btn_6_6->setFlat(true);
        btn_startgame = new QPushButton(netpan);
        btn_startgame->setObjectName(QString::fromUtf8("btn_startgame"));
        btn_startgame->setGeometry(QRect(790, 260, 91, 61));
        btn_3_3 = new QPushButton(netpan);
        btn_3_3->setObjectName(QString::fromUtf8("btn_3_3"));
        btn_3_3->setEnabled(true);
        btn_3_3->setGeometry(QRect(280, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_3->sizePolicy().hasHeightForWidth());
        btn_3_3->setSizePolicy(sizePolicy);
        btn_3_3->setMinimumSize(QSize(50, 50));
        btn_3_3->setMaximumSize(QSize(60, 50));
        btn_3_3->setStyleSheet(QString::fromUtf8(""));
        btn_3_3->setFlat(true);
        btn_6_5 = new QPushButton(netpan);
        btn_6_5->setObjectName(QString::fromUtf8("btn_6_5"));
        btn_6_5->setEnabled(true);
        btn_6_5->setGeometry(QRect(380, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_5->sizePolicy().hasHeightForWidth());
        btn_6_5->setSizePolicy(sizePolicy);
        btn_6_5->setMinimumSize(QSize(50, 50));
        btn_6_5->setMaximumSize(QSize(60, 50));
        btn_6_5->setStyleSheet(QString::fromUtf8(""));
        btn_6_5->setFlat(true);
        btn_2_7 = new QPushButton(netpan);
        btn_2_7->setObjectName(QString::fromUtf8("btn_2_7"));
        btn_2_7->setEnabled(true);
        btn_2_7->setGeometry(QRect(480, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_7->sizePolicy().hasHeightForWidth());
        btn_2_7->setSizePolicy(sizePolicy);
        btn_2_7->setMinimumSize(QSize(50, 50));
        btn_2_7->setMaximumSize(QSize(60, 50));
        btn_2_7->setStyleSheet(QString::fromUtf8(""));
        btn_2_7->setFlat(true);
        btn_6_4 = new QPushButton(netpan);
        btn_6_4->setObjectName(QString::fromUtf8("btn_6_4"));
        btn_6_4->setEnabled(true);
        btn_6_4->setGeometry(QRect(330, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_4->sizePolicy().hasHeightForWidth());
        btn_6_4->setSizePolicy(sizePolicy);
        btn_6_4->setMinimumSize(QSize(50, 50));
        btn_6_4->setMaximumSize(QSize(60, 50));
        btn_6_4->setStyleSheet(QString::fromUtf8(""));
        btn_6_4->setFlat(true);
        btn_2_5 = new QPushButton(netpan);
        btn_2_5->setObjectName(QString::fromUtf8("btn_2_5"));
        btn_2_5->setEnabled(true);
        btn_2_5->setGeometry(QRect(380, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_5->sizePolicy().hasHeightForWidth());
        btn_2_5->setSizePolicy(sizePolicy);
        btn_2_5->setMinimumSize(QSize(50, 50));
        btn_2_5->setMaximumSize(QSize(60, 50));
        btn_2_5->setStyleSheet(QString::fromUtf8(""));
        btn_2_5->setFlat(true);
        btn_2_1 = new QPushButton(netpan);
        btn_2_1->setObjectName(QString::fromUtf8("btn_2_1"));
        btn_2_1->setEnabled(true);
        btn_2_1->setGeometry(QRect(180, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_1->sizePolicy().hasHeightForWidth());
        btn_2_1->setSizePolicy(sizePolicy);
        btn_2_1->setMinimumSize(QSize(50, 50));
        btn_2_1->setMaximumSize(QSize(60, 50));
        btn_2_1->setStyleSheet(QString::fromUtf8(""));
        btn_2_1->setFlat(true);
        btn_3_0 = new QPushButton(netpan);
        btn_3_0->setObjectName(QString::fromUtf8("btn_3_0"));
        btn_3_0->setEnabled(true);
        btn_3_0->setGeometry(QRect(130, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_0->sizePolicy().hasHeightForWidth());
        btn_3_0->setSizePolicy(sizePolicy);
        btn_3_0->setMinimumSize(QSize(50, 50));
        btn_3_0->setMaximumSize(QSize(60, 50));
        btn_3_0->setStyleSheet(QString::fromUtf8(""));
        btn_3_0->setFlat(true);
        btn_0_1 = new QPushButton(netpan);
        btn_0_1->setObjectName(QString::fromUtf8("btn_0_1"));
        btn_0_1->setEnabled(true);
        btn_0_1->setGeometry(QRect(180, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_1->sizePolicy().hasHeightForWidth());
        btn_0_1->setSizePolicy(sizePolicy);
        btn_0_1->setMinimumSize(QSize(50, 50));
        btn_0_1->setMaximumSize(QSize(60, 50));
        btn_0_1->setStyleSheet(QString::fromUtf8(""));
        btn_0_1->setFlat(true);
        btn_0_3 = new QPushButton(netpan);
        btn_0_3->setObjectName(QString::fromUtf8("btn_0_3"));
        btn_0_3->setEnabled(true);
        btn_0_3->setGeometry(QRect(280, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_3->sizePolicy().hasHeightForWidth());
        btn_0_3->setSizePolicy(sizePolicy);
        btn_0_3->setMinimumSize(QSize(50, 50));
        btn_0_3->setMaximumSize(QSize(60, 50));
        btn_0_3->setStyleSheet(QString::fromUtf8(""));
        btn_0_3->setFlat(true);
        btn_5_1 = new QPushButton(netpan);
        btn_5_1->setObjectName(QString::fromUtf8("btn_5_1"));
        btn_5_1->setEnabled(true);
        btn_5_1->setGeometry(QRect(180, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_1->sizePolicy().hasHeightForWidth());
        btn_5_1->setSizePolicy(sizePolicy);
        btn_5_1->setMinimumSize(QSize(50, 50));
        btn_5_1->setMaximumSize(QSize(60, 50));
        btn_5_1->setStyleSheet(QString::fromUtf8(""));
        btn_5_1->setFlat(true);
        btn_6_1 = new QPushButton(netpan);
        btn_6_1->setObjectName(QString::fromUtf8("btn_6_1"));
        btn_6_1->setEnabled(true);
        btn_6_1->setGeometry(QRect(180, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_1->sizePolicy().hasHeightForWidth());
        btn_6_1->setSizePolicy(sizePolicy);
        btn_6_1->setMinimumSize(QSize(50, 50));
        btn_6_1->setMaximumSize(QSize(60, 50));
        btn_6_1->setStyleSheet(QString::fromUtf8(""));
        btn_6_1->setFlat(true);
        btn_1_5 = new QPushButton(netpan);
        btn_1_5->setObjectName(QString::fromUtf8("btn_1_5"));
        btn_1_5->setEnabled(true);
        btn_1_5->setGeometry(QRect(380, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_5->sizePolicy().hasHeightForWidth());
        btn_1_5->setSizePolicy(sizePolicy);
        btn_1_5->setMinimumSize(QSize(50, 50));
        btn_1_5->setMaximumSize(QSize(60, 50));
        btn_1_5->setStyleSheet(QString::fromUtf8(""));
        btn_1_5->setFlat(true);
        btn_5_4 = new QPushButton(netpan);
        btn_5_4->setObjectName(QString::fromUtf8("btn_5_4"));
        btn_5_4->setEnabled(true);
        btn_5_4->setGeometry(QRect(330, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_4->sizePolicy().hasHeightForWidth());
        btn_5_4->setSizePolicy(sizePolicy);
        btn_5_4->setMinimumSize(QSize(50, 50));
        btn_5_4->setMaximumSize(QSize(60, 50));
        btn_5_4->setStyleSheet(QString::fromUtf8(""));
        btn_5_4->setFlat(true);
        btn_7_8 = new QPushButton(netpan);
        btn_7_8->setObjectName(QString::fromUtf8("btn_7_8"));
        btn_7_8->setEnabled(true);
        btn_7_8->setGeometry(QRect(530, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_8->sizePolicy().hasHeightForWidth());
        btn_7_8->setSizePolicy(sizePolicy);
        btn_7_8->setMinimumSize(QSize(50, 50));
        btn_7_8->setMaximumSize(QSize(60, 50));
        btn_7_8->setStyleSheet(QString::fromUtf8(""));
        btn_7_8->setFlat(true);
        btn_8_7 = new QPushButton(netpan);
        btn_8_7->setObjectName(QString::fromUtf8("btn_8_7"));
        btn_8_7->setEnabled(true);
        btn_8_7->setGeometry(QRect(480, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_7->sizePolicy().hasHeightForWidth());
        btn_8_7->setSizePolicy(sizePolicy);
        btn_8_7->setMinimumSize(QSize(50, 50));
        btn_8_7->setMaximumSize(QSize(60, 50));
        btn_8_7->setStyleSheet(QString::fromUtf8(""));
        btn_8_7->setFlat(true);
        btn_2_4 = new QPushButton(netpan);
        btn_2_4->setObjectName(QString::fromUtf8("btn_2_4"));
        btn_2_4->setEnabled(true);
        btn_2_4->setGeometry(QRect(330, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_4->sizePolicy().hasHeightForWidth());
        btn_2_4->setSizePolicy(sizePolicy);
        btn_2_4->setMinimumSize(QSize(50, 50));
        btn_2_4->setMaximumSize(QSize(60, 50));
        btn_2_4->setStyleSheet(QString::fromUtf8(""));
        btn_2_4->setFlat(true);
        btn_8_1 = new QPushButton(netpan);
        btn_8_1->setObjectName(QString::fromUtf8("btn_8_1"));
        btn_8_1->setEnabled(true);
        btn_8_1->setGeometry(QRect(180, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_1->sizePolicy().hasHeightForWidth());
        btn_8_1->setSizePolicy(sizePolicy);
        btn_8_1->setMinimumSize(QSize(50, 50));
        btn_8_1->setMaximumSize(QSize(60, 50));
        btn_8_1->setStyleSheet(QString::fromUtf8(""));
        btn_8_1->setFlat(true);
        txtl_pan_time = new QLineEdit(netpan);
        txtl_pan_time->setObjectName(QString::fromUtf8("txtl_pan_time"));
        txtl_pan_time->setEnabled(true);
        txtl_pan_time->setGeometry(QRect(830, 150, 131, 81));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Gigi")});
        font1.setPointSize(36);
        font1.setBold(false);
        font1.setItalic(false);
        txtl_pan_time->setFont(font1);
        btn_3_5 = new QPushButton(netpan);
        btn_3_5->setObjectName(QString::fromUtf8("btn_3_5"));
        btn_3_5->setEnabled(true);
        btn_3_5->setGeometry(QRect(380, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_5->sizePolicy().hasHeightForWidth());
        btn_3_5->setSizePolicy(sizePolicy);
        btn_3_5->setMinimumSize(QSize(50, 50));
        btn_3_5->setMaximumSize(QSize(60, 50));
        btn_3_5->setStyleSheet(QString::fromUtf8(""));
        btn_3_5->setFlat(true);
        label = new QLabel(netpan);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(750, 150, 81, 31));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        label->setFont(font2);
        btn_2_0 = new QPushButton(netpan);
        btn_2_0->setObjectName(QString::fromUtf8("btn_2_0"));
        btn_2_0->setEnabled(true);
        btn_2_0->setGeometry(QRect(130, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_0->sizePolicy().hasHeightForWidth());
        btn_2_0->setSizePolicy(sizePolicy);
        btn_2_0->setMinimumSize(QSize(50, 50));
        btn_2_0->setMaximumSize(QSize(60, 50));
        btn_2_0->setStyleSheet(QString::fromUtf8(""));
        btn_2_0->setFlat(true);
        btn_2_2 = new QPushButton(netpan);
        btn_2_2->setObjectName(QString::fromUtf8("btn_2_2"));
        btn_2_2->setEnabled(true);
        btn_2_2->setGeometry(QRect(230, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_2->sizePolicy().hasHeightForWidth());
        btn_2_2->setSizePolicy(sizePolicy);
        btn_2_2->setMinimumSize(QSize(50, 50));
        btn_2_2->setMaximumSize(QSize(60, 50));
        btn_2_2->setStyleSheet(QString::fromUtf8(""));
        btn_2_2->setFlat(true);
        btn_5_0 = new QPushButton(netpan);
        btn_5_0->setObjectName(QString::fromUtf8("btn_5_0"));
        btn_5_0->setEnabled(true);
        btn_5_0->setGeometry(QRect(130, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_0->sizePolicy().hasHeightForWidth());
        btn_5_0->setSizePolicy(sizePolicy);
        btn_5_0->setMinimumSize(QSize(50, 50));
        btn_5_0->setMaximumSize(QSize(60, 50));
        btn_5_0->setStyleSheet(QString::fromUtf8(""));
        btn_5_0->setFlat(true);
        btn_2_8 = new QPushButton(netpan);
        btn_2_8->setObjectName(QString::fromUtf8("btn_2_8"));
        btn_2_8->setEnabled(true);
        btn_2_8->setGeometry(QRect(530, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_8->sizePolicy().hasHeightForWidth());
        btn_2_8->setSizePolicy(sizePolicy);
        btn_2_8->setMinimumSize(QSize(50, 50));
        btn_2_8->setMaximumSize(QSize(60, 50));
        btn_2_8->setStyleSheet(QString::fromUtf8(""));
        btn_2_8->setFlat(true);
        btn_4_6 = new QPushButton(netpan);
        btn_4_6->setObjectName(QString::fromUtf8("btn_4_6"));
        btn_4_6->setEnabled(true);
        btn_4_6->setGeometry(QRect(430, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_6->sizePolicy().hasHeightForWidth());
        btn_4_6->setSizePolicy(sizePolicy);
        btn_4_6->setMinimumSize(QSize(50, 50));
        btn_4_6->setMaximumSize(QSize(60, 50));
        btn_4_6->setStyleSheet(QString::fromUtf8(""));
        btn_4_6->setFlat(true);
        btn_white = new QPushButton(netpan);
        btn_white->setObjectName(QString::fromUtf8("btn_white"));
        btn_white->setEnabled(false);
        btn_white->setGeometry(QRect(970, 450, 50, 50));
        sizePolicy.setHeightForWidth(btn_white->sizePolicy().hasHeightForWidth());
        btn_white->setSizePolicy(sizePolicy);
        btn_white->setMinimumSize(QSize(50, 50));
        btn_white->setMaximumSize(QSize(60, 50));
        btn_white->setStyleSheet(QString::fromUtf8(""));
        btn_white->setFlat(true);
        btn_7_3 = new QPushButton(netpan);
        btn_7_3->setObjectName(QString::fromUtf8("btn_7_3"));
        btn_7_3->setEnabled(true);
        btn_7_3->setGeometry(QRect(280, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_3->sizePolicy().hasHeightForWidth());
        btn_7_3->setSizePolicy(sizePolicy);
        btn_7_3->setMinimumSize(QSize(50, 50));
        btn_7_3->setMaximumSize(QSize(60, 50));
        btn_7_3->setStyleSheet(QString::fromUtf8(""));
        btn_7_3->setFlat(true);
        btn_5_6 = new QPushButton(netpan);
        btn_5_6->setObjectName(QString::fromUtf8("btn_5_6"));
        btn_5_6->setEnabled(true);
        btn_5_6->setGeometry(QRect(430, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_6->sizePolicy().hasHeightForWidth());
        btn_5_6->setSizePolicy(sizePolicy);
        btn_5_6->setMinimumSize(QSize(50, 50));
        btn_5_6->setMaximumSize(QSize(60, 50));
        btn_5_6->setStyleSheet(QString::fromUtf8(""));
        btn_5_6->setFlat(true);
        btn_restart = new QPushButton(netpan);
        btn_restart->setObjectName(QString::fromUtf8("btn_restart"));
        btn_restart->setGeometry(QRect(900, 330, 91, 61));
        btn_2_6 = new QPushButton(netpan);
        btn_2_6->setObjectName(QString::fromUtf8("btn_2_6"));
        btn_2_6->setEnabled(true);
        btn_2_6->setGeometry(QRect(430, 230, 50, 50));
        sizePolicy.setHeightForWidth(btn_2_6->sizePolicy().hasHeightForWidth());
        btn_2_6->setSizePolicy(sizePolicy);
        btn_2_6->setMinimumSize(QSize(50, 50));
        btn_2_6->setMaximumSize(QSize(60, 50));
        btn_2_6->setStyleSheet(QString::fromUtf8(""));
        btn_2_6->setFlat(true);
        btn_0_2 = new QPushButton(netpan);
        btn_0_2->setObjectName(QString::fromUtf8("btn_0_2"));
        btn_0_2->setEnabled(true);
        btn_0_2->setGeometry(QRect(230, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_2->sizePolicy().hasHeightForWidth());
        btn_0_2->setSizePolicy(sizePolicy);
        btn_0_2->setMinimumSize(QSize(50, 50));
        btn_0_2->setMaximumSize(QSize(60, 50));
        btn_0_2->setStyleSheet(QString::fromUtf8(""));
        btn_0_2->setFlat(true);
        btn_1_1 = new QPushButton(netpan);
        btn_1_1->setObjectName(QString::fromUtf8("btn_1_1"));
        btn_1_1->setEnabled(true);
        btn_1_1->setGeometry(QRect(180, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_1->sizePolicy().hasHeightForWidth());
        btn_1_1->setSizePolicy(sizePolicy);
        btn_1_1->setMinimumSize(QSize(50, 50));
        btn_1_1->setMaximumSize(QSize(60, 50));
        btn_1_1->setStyleSheet(QString::fromUtf8(""));
        btn_1_1->setFlat(true);
        btn_4_5 = new QPushButton(netpan);
        btn_4_5->setObjectName(QString::fromUtf8("btn_4_5"));
        btn_4_5->setEnabled(true);
        btn_4_5->setGeometry(QRect(380, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_5->sizePolicy().hasHeightForWidth());
        btn_4_5->setSizePolicy(sizePolicy);
        btn_4_5->setMinimumSize(QSize(50, 50));
        btn_4_5->setMaximumSize(QSize(60, 50));
        btn_4_5->setStyleSheet(QString::fromUtf8(""));
        btn_4_5->setFlat(true);
        btn_3_4 = new QPushButton(netpan);
        btn_3_4->setObjectName(QString::fromUtf8("btn_3_4"));
        btn_3_4->setEnabled(true);
        btn_3_4->setGeometry(QRect(330, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_4->sizePolicy().hasHeightForWidth());
        btn_3_4->setSizePolicy(sizePolicy);
        btn_3_4->setMinimumSize(QSize(50, 50));
        btn_3_4->setMaximumSize(QSize(60, 50));
        btn_3_4->setStyleSheet(QString::fromUtf8(""));
        btn_3_4->setFlat(true);
        btn_6_7 = new QPushButton(netpan);
        btn_6_7->setObjectName(QString::fromUtf8("btn_6_7"));
        btn_6_7->setEnabled(true);
        btn_6_7->setGeometry(QRect(480, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_7->sizePolicy().hasHeightForWidth());
        btn_6_7->setSizePolicy(sizePolicy);
        btn_6_7->setMinimumSize(QSize(50, 50));
        btn_6_7->setMaximumSize(QSize(60, 50));
        btn_6_7->setStyleSheet(QString::fromUtf8(""));
        btn_6_7->setFlat(true);
        btn_4_7 = new QPushButton(netpan);
        btn_4_7->setObjectName(QString::fromUtf8("btn_4_7"));
        btn_4_7->setEnabled(true);
        btn_4_7->setGeometry(QRect(480, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_7->sizePolicy().hasHeightForWidth());
        btn_4_7->setSizePolicy(sizePolicy);
        btn_4_7->setMinimumSize(QSize(50, 50));
        btn_4_7->setMaximumSize(QSize(60, 50));
        btn_4_7->setStyleSheet(QString::fromUtf8(""));
        btn_4_7->setFlat(true);
        btn_4_0 = new QPushButton(netpan);
        btn_4_0->setObjectName(QString::fromUtf8("btn_4_0"));
        btn_4_0->setEnabled(true);
        btn_4_0->setGeometry(QRect(130, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_0->sizePolicy().hasHeightForWidth());
        btn_4_0->setSizePolicy(sizePolicy);
        btn_4_0->setMinimumSize(QSize(50, 50));
        btn_4_0->setMaximumSize(QSize(60, 50));
        btn_4_0->setStyleSheet(QString::fromUtf8(""));
        btn_4_0->setFlat(true);
        btn_8_0 = new QPushButton(netpan);
        btn_8_0->setObjectName(QString::fromUtf8("btn_8_0"));
        btn_8_0->setEnabled(true);
        btn_8_0->setGeometry(QRect(130, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_0->sizePolicy().hasHeightForWidth());
        btn_8_0->setSizePolicy(sizePolicy);
        btn_8_0->setMinimumSize(QSize(50, 50));
        btn_8_0->setMaximumSize(QSize(60, 50));
        btn_8_0->setStyleSheet(QString::fromUtf8(""));
        btn_8_0->setFlat(true);
        btn_3_2 = new QPushButton(netpan);
        btn_3_2->setObjectName(QString::fromUtf8("btn_3_2"));
        btn_3_2->setEnabled(true);
        btn_3_2->setGeometry(QRect(230, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_2->sizePolicy().hasHeightForWidth());
        btn_3_2->setSizePolicy(sizePolicy);
        btn_3_2->setMinimumSize(QSize(50, 50));
        btn_3_2->setMaximumSize(QSize(60, 50));
        btn_3_2->setStyleSheet(QString::fromUtf8(""));
        btn_3_2->setFlat(true);
        btn_0_0 = new QPushButton(netpan);
        btn_0_0->setObjectName(QString::fromUtf8("btn_0_0"));
        btn_0_0->setEnabled(true);
        btn_0_0->setGeometry(QRect(130, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_0->sizePolicy().hasHeightForWidth());
        btn_0_0->setSizePolicy(sizePolicy);
        btn_0_0->setMinimumSize(QSize(50, 50));
        btn_0_0->setMaximumSize(QSize(60, 50));
        btn_0_0->setStyleSheet(QString::fromUtf8(""));
        btn_0_0->setFlat(true);
        btn_3_8 = new QPushButton(netpan);
        btn_3_8->setObjectName(QString::fromUtf8("btn_3_8"));
        btn_3_8->setEnabled(true);
        btn_3_8->setGeometry(QRect(530, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_8->sizePolicy().hasHeightForWidth());
        btn_3_8->setSizePolicy(sizePolicy);
        btn_3_8->setMinimumSize(QSize(50, 50));
        btn_3_8->setMaximumSize(QSize(60, 50));
        btn_3_8->setStyleSheet(QString::fromUtf8(""));
        btn_3_8->setFlat(true);
        btn_0_7 = new QPushButton(netpan);
        btn_0_7->setObjectName(QString::fromUtf8("btn_0_7"));
        btn_0_7->setEnabled(true);
        btn_0_7->setGeometry(QRect(480, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_7->sizePolicy().hasHeightForWidth());
        btn_0_7->setSizePolicy(sizePolicy);
        btn_0_7->setMinimumSize(QSize(50, 50));
        btn_0_7->setMaximumSize(QSize(60, 50));
        btn_0_7->setStyleSheet(QString::fromUtf8(""));
        btn_0_7->setFlat(true);
        label_3 = new QLabel(netpan);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(870, 510, 69, 71));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Informal Roman")});
        font3.setPointSize(28);
        label_3->setFont(font3);
        btn_7_1 = new QPushButton(netpan);
        btn_7_1->setObjectName(QString::fromUtf8("btn_7_1"));
        btn_7_1->setEnabled(true);
        btn_7_1->setGeometry(QRect(180, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_1->sizePolicy().hasHeightForWidth());
        btn_7_1->setSizePolicy(sizePolicy);
        btn_7_1->setMinimumSize(QSize(50, 50));
        btn_7_1->setMaximumSize(QSize(60, 50));
        btn_7_1->setStyleSheet(QString::fromUtf8(""));
        btn_7_1->setFlat(true);
        btn_black = new QPushButton(netpan);
        btn_black->setObjectName(QString::fromUtf8("btn_black"));
        btn_black->setEnabled(false);
        btn_black->setGeometry(QRect(780, 450, 50, 50));
        sizePolicy.setHeightForWidth(btn_black->sizePolicy().hasHeightForWidth());
        btn_black->setSizePolicy(sizePolicy);
        btn_black->setMinimumSize(QSize(50, 50));
        btn_black->setMaximumSize(QSize(60, 50));
        btn_black->setStyleSheet(QString::fromUtf8(""));
        btn_black->setFlat(true);
        btn_0_5 = new QPushButton(netpan);
        btn_0_5->setObjectName(QString::fromUtf8("btn_0_5"));
        btn_0_5->setEnabled(true);
        btn_0_5->setGeometry(QRect(380, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_5->sizePolicy().hasHeightForWidth());
        btn_0_5->setSizePolicy(sizePolicy);
        btn_0_5->setMinimumSize(QSize(50, 50));
        btn_0_5->setMaximumSize(QSize(60, 50));
        btn_0_5->setStyleSheet(QString::fromUtf8(""));
        btn_0_5->setFlat(true);
        btn_6_0 = new QPushButton(netpan);
        btn_6_0->setObjectName(QString::fromUtf8("btn_6_0"));
        btn_6_0->setEnabled(true);
        btn_6_0->setGeometry(QRect(130, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_0->sizePolicy().hasHeightForWidth());
        btn_6_0->setSizePolicy(sizePolicy);
        btn_6_0->setMinimumSize(QSize(50, 50));
        btn_6_0->setMaximumSize(QSize(60, 50));
        btn_6_0->setStyleSheet(QString::fromUtf8(""));
        btn_6_0->setFlat(true);
        btn_0_4 = new QPushButton(netpan);
        btn_0_4->setObjectName(QString::fromUtf8("btn_0_4"));
        btn_0_4->setEnabled(true);
        btn_0_4->setGeometry(QRect(330, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_4->sizePolicy().hasHeightForWidth());
        btn_0_4->setSizePolicy(sizePolicy);
        btn_0_4->setMinimumSize(QSize(50, 50));
        btn_0_4->setMaximumSize(QSize(60, 50));
        btn_0_4->setStyleSheet(QString::fromUtf8(""));
        btn_0_4->setFlat(true);
        btn_7_7 = new QPushButton(netpan);
        btn_7_7->setObjectName(QString::fromUtf8("btn_7_7"));
        btn_7_7->setEnabled(true);
        btn_7_7->setGeometry(QRect(480, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_7->sizePolicy().hasHeightForWidth());
        btn_7_7->setSizePolicy(sizePolicy);
        btn_7_7->setMinimumSize(QSize(50, 50));
        btn_7_7->setMaximumSize(QSize(60, 50));
        btn_7_7->setStyleSheet(QString::fromUtf8(""));
        btn_7_7->setFlat(true);
        btn_4_2 = new QPushButton(netpan);
        btn_4_2->setObjectName(QString::fromUtf8("btn_4_2"));
        btn_4_2->setEnabled(true);
        btn_4_2->setGeometry(QRect(230, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_2->sizePolicy().hasHeightForWidth());
        btn_4_2->setSizePolicy(sizePolicy);
        btn_4_2->setMinimumSize(QSize(50, 50));
        btn_4_2->setMaximumSize(QSize(60, 50));
        btn_4_2->setStyleSheet(QString::fromUtf8(""));
        btn_4_2->setFlat(true);
        btn_6_3 = new QPushButton(netpan);
        btn_6_3->setObjectName(QString::fromUtf8("btn_6_3"));
        btn_6_3->setEnabled(true);
        btn_6_3->setGeometry(QRect(280, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_3->sizePolicy().hasHeightForWidth());
        btn_6_3->setSizePolicy(sizePolicy);
        btn_6_3->setMinimumSize(QSize(50, 50));
        btn_6_3->setMaximumSize(QSize(60, 50));
        btn_6_3->setStyleSheet(QString::fromUtf8(""));
        btn_6_3->setFlat(true);
        btn_5_7 = new QPushButton(netpan);
        btn_5_7->setObjectName(QString::fromUtf8("btn_5_7"));
        btn_5_7->setEnabled(true);
        btn_5_7->setGeometry(QRect(480, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_7->sizePolicy().hasHeightForWidth());
        btn_5_7->setSizePolicy(sizePolicy);
        btn_5_7->setMinimumSize(QSize(50, 50));
        btn_5_7->setMaximumSize(QSize(60, 50));
        btn_5_7->setStyleSheet(QString::fromUtf8(""));
        btn_5_7->setFlat(true);
        btn_7_0 = new QPushButton(netpan);
        btn_7_0->setObjectName(QString::fromUtf8("btn_7_0"));
        btn_7_0->setEnabled(true);
        btn_7_0->setGeometry(QRect(130, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_0->sizePolicy().hasHeightForWidth());
        btn_7_0->setSizePolicy(sizePolicy);
        btn_7_0->setMinimumSize(QSize(50, 50));
        btn_7_0->setMaximumSize(QSize(60, 50));
        btn_7_0->setStyleSheet(QString::fromUtf8(""));
        btn_7_0->setFlat(true);
        btn_6_8 = new QPushButton(netpan);
        btn_6_8->setObjectName(QString::fromUtf8("btn_6_8"));
        btn_6_8->setEnabled(true);
        btn_6_8->setGeometry(QRect(530, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_8->sizePolicy().hasHeightForWidth());
        btn_6_8->setSizePolicy(sizePolicy);
        btn_6_8->setMinimumSize(QSize(50, 50));
        btn_6_8->setMaximumSize(QSize(60, 50));
        btn_6_8->setStyleSheet(QString::fromUtf8(""));
        btn_6_8->setFlat(true);
        btn_4_4 = new QPushButton(netpan);
        btn_4_4->setObjectName(QString::fromUtf8("btn_4_4"));
        btn_4_4->setEnabled(true);
        btn_4_4->setGeometry(QRect(330, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_4->sizePolicy().hasHeightForWidth());
        btn_4_4->setSizePolicy(sizePolicy);
        btn_4_4->setMinimumSize(QSize(50, 50));
        btn_4_4->setMaximumSize(QSize(60, 50));
        btn_4_4->setStyleSheet(QString::fromUtf8(""));
        btn_4_4->setFlat(true);
        btn_4_3 = new QPushButton(netpan);
        btn_4_3->setObjectName(QString::fromUtf8("btn_4_3"));
        btn_4_3->setEnabled(true);
        btn_4_3->setGeometry(QRect(280, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_3->sizePolicy().hasHeightForWidth());
        btn_4_3->setSizePolicy(sizePolicy);
        btn_4_3->setMinimumSize(QSize(50, 50));
        btn_4_3->setMaximumSize(QSize(60, 50));
        btn_4_3->setStyleSheet(QString::fromUtf8(""));
        btn_4_3->setFlat(true);
        btn_8_6 = new QPushButton(netpan);
        btn_8_6->setObjectName(QString::fromUtf8("btn_8_6"));
        btn_8_6->setEnabled(true);
        btn_8_6->setGeometry(QRect(430, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_6->sizePolicy().hasHeightForWidth());
        btn_8_6->setSizePolicy(sizePolicy);
        btn_8_6->setMinimumSize(QSize(50, 50));
        btn_8_6->setMaximumSize(QSize(60, 50));
        btn_8_6->setStyleSheet(QString::fromUtf8(""));
        btn_8_6->setFlat(true);
        btn_6_2 = new QPushButton(netpan);
        btn_6_2->setObjectName(QString::fromUtf8("btn_6_2"));
        btn_6_2->setEnabled(true);
        btn_6_2->setGeometry(QRect(230, 430, 50, 50));
        sizePolicy.setHeightForWidth(btn_6_2->sizePolicy().hasHeightForWidth());
        btn_6_2->setSizePolicy(sizePolicy);
        btn_6_2->setMinimumSize(QSize(50, 50));
        btn_6_2->setMaximumSize(QSize(60, 50));
        btn_6_2->setStyleSheet(QString::fromUtf8(""));
        btn_6_2->setFlat(true);
        btn_7_6 = new QPushButton(netpan);
        btn_7_6->setObjectName(QString::fromUtf8("btn_7_6"));
        btn_7_6->setEnabled(true);
        btn_7_6->setGeometry(QRect(430, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_6->sizePolicy().hasHeightForWidth());
        btn_7_6->setSizePolicy(sizePolicy);
        btn_7_6->setMinimumSize(QSize(50, 50));
        btn_7_6->setMaximumSize(QSize(60, 50));
        btn_7_6->setStyleSheet(QString::fromUtf8(""));
        btn_7_6->setFlat(true);
        btn_stop = new QPushButton(netpan);
        btn_stop->setObjectName(QString::fromUtf8("btn_stop"));
        btn_stop->setGeometry(QRect(900, 260, 91, 61));
        back = new QPushButton(netpan);
        back->setObjectName(QString::fromUtf8("back"));
        back->setGeometry(QRect(1090, 10, 51, 51));
        QFont font4;
        font4.setBold(true);
        back->setFont(font4);
        btn_3_7 = new QPushButton(netpan);
        btn_3_7->setObjectName(QString::fromUtf8("btn_3_7"));
        btn_3_7->setEnabled(true);
        btn_3_7->setGeometry(QRect(480, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_7->sizePolicy().hasHeightForWidth());
        btn_3_7->setSizePolicy(sizePolicy);
        btn_3_7->setMinimumSize(QSize(50, 50));
        btn_3_7->setMaximumSize(QSize(60, 50));
        btn_3_7->setStyleSheet(QString::fromUtf8(""));
        btn_3_7->setFlat(true);
        btn_8_2 = new QPushButton(netpan);
        btn_8_2->setObjectName(QString::fromUtf8("btn_8_2"));
        btn_8_2->setEnabled(true);
        btn_8_2->setGeometry(QRect(230, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_2->sizePolicy().hasHeightForWidth());
        btn_8_2->setSizePolicy(sizePolicy);
        btn_8_2->setMinimumSize(QSize(50, 50));
        btn_8_2->setMaximumSize(QSize(60, 50));
        btn_8_2->setStyleSheet(QString::fromUtf8(""));
        btn_8_2->setFlat(true);
        btn_1_8 = new QPushButton(netpan);
        btn_1_8->setObjectName(QString::fromUtf8("btn_1_8"));
        btn_1_8->setEnabled(true);
        btn_1_8->setGeometry(QRect(530, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_8->sizePolicy().hasHeightForWidth());
        btn_1_8->setSizePolicy(sizePolicy);
        btn_1_8->setMinimumSize(QSize(50, 50));
        btn_1_8->setMaximumSize(QSize(60, 50));
        btn_1_8->setStyleSheet(QString::fromUtf8(""));
        btn_1_8->setFlat(true);
        btn_5_2 = new QPushButton(netpan);
        btn_5_2->setObjectName(QString::fromUtf8("btn_5_2"));
        btn_5_2->setEnabled(true);
        btn_5_2->setGeometry(QRect(230, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_2->sizePolicy().hasHeightForWidth());
        btn_5_2->setSizePolicy(sizePolicy);
        btn_5_2->setMinimumSize(QSize(50, 50));
        btn_5_2->setMaximumSize(QSize(60, 50));
        btn_5_2->setStyleSheet(QString::fromUtf8(""));
        btn_5_2->setFlat(true);
        line_player_1 = new QLineEdit(netpan);
        line_player_1->setObjectName(QString::fromUtf8("line_player_1"));
        line_player_1->setGeometry(QRect(950, 520, 91, 51));
        line_player_1->setFont(font);
        btn_0_8 = new QPushButton(netpan);
        btn_0_8->setObjectName(QString::fromUtf8("btn_0_8"));
        btn_0_8->setEnabled(true);
        btn_0_8->setGeometry(QRect(530, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_8->sizePolicy().hasHeightForWidth());
        btn_0_8->setSizePolicy(sizePolicy);
        btn_0_8->setMinimumSize(QSize(50, 50));
        btn_0_8->setMaximumSize(QSize(60, 50));
        btn_0_8->setStyleSheet(QString::fromUtf8(""));
        btn_0_8->setFlat(true);
        btn_7_4 = new QPushButton(netpan);
        btn_7_4->setObjectName(QString::fromUtf8("btn_7_4"));
        btn_7_4->setEnabled(true);
        btn_7_4->setGeometry(QRect(330, 480, 50, 50));
        sizePolicy.setHeightForWidth(btn_7_4->sizePolicy().hasHeightForWidth());
        btn_7_4->setSizePolicy(sizePolicy);
        btn_7_4->setMinimumSize(QSize(50, 50));
        btn_7_4->setMaximumSize(QSize(60, 50));
        btn_7_4->setStyleSheet(QString::fromUtf8(""));
        btn_7_4->setFlat(true);
        btn_4_8 = new QPushButton(netpan);
        btn_4_8->setObjectName(QString::fromUtf8("btn_4_8"));
        btn_4_8->setEnabled(true);
        btn_4_8->setGeometry(QRect(530, 330, 50, 50));
        sizePolicy.setHeightForWidth(btn_4_8->sizePolicy().hasHeightForWidth());
        btn_4_8->setSizePolicy(sizePolicy);
        btn_4_8->setMinimumSize(QSize(50, 50));
        btn_4_8->setMaximumSize(QSize(60, 50));
        btn_4_8->setStyleSheet(QString::fromUtf8(""));
        btn_4_8->setFlat(true);
        btn_0_6 = new QPushButton(netpan);
        btn_0_6->setObjectName(QString::fromUtf8("btn_0_6"));
        btn_0_6->setEnabled(true);
        btn_0_6->setGeometry(QRect(430, 130, 50, 50));
        sizePolicy.setHeightForWidth(btn_0_6->sizePolicy().hasHeightForWidth());
        btn_0_6->setSizePolicy(sizePolicy);
        btn_0_6->setMinimumSize(QSize(50, 50));
        btn_0_6->setMaximumSize(QSize(60, 50));
        btn_0_6->setStyleSheet(QString::fromUtf8(""));
        btn_0_6->setFlat(true);
        btn_1_3 = new QPushButton(netpan);
        btn_1_3->setObjectName(QString::fromUtf8("btn_1_3"));
        btn_1_3->setEnabled(true);
        btn_1_3->setGeometry(QRect(280, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_3->sizePolicy().hasHeightForWidth());
        btn_1_3->setSizePolicy(sizePolicy);
        btn_1_3->setMinimumSize(QSize(50, 50));
        btn_1_3->setMaximumSize(QSize(60, 50));
        btn_1_3->setStyleSheet(QString::fromUtf8(""));
        btn_1_3->setFlat(true);
        btn_3_1 = new QPushButton(netpan);
        btn_3_1->setObjectName(QString::fromUtf8("btn_3_1"));
        btn_3_1->setEnabled(true);
        btn_3_1->setGeometry(QRect(180, 280, 50, 50));
        sizePolicy.setHeightForWidth(btn_3_1->sizePolicy().hasHeightForWidth());
        btn_3_1->setSizePolicy(sizePolicy);
        btn_3_1->setMinimumSize(QSize(50, 50));
        btn_3_1->setMaximumSize(QSize(60, 50));
        btn_3_1->setStyleSheet(QString::fromUtf8(""));
        btn_3_1->setFlat(true);
        btn_5_3 = new QPushButton(netpan);
        btn_5_3->setObjectName(QString::fromUtf8("btn_5_3"));
        btn_5_3->setEnabled(true);
        btn_5_3->setGeometry(QRect(280, 380, 50, 50));
        sizePolicy.setHeightForWidth(btn_5_3->sizePolicy().hasHeightForWidth());
        btn_5_3->setSizePolicy(sizePolicy);
        btn_5_3->setMinimumSize(QSize(50, 50));
        btn_5_3->setMaximumSize(QSize(60, 50));
        btn_5_3->setStyleSheet(QString::fromUtf8(""));
        btn_5_3->setFlat(true);
        btn_1_4 = new QPushButton(netpan);
        btn_1_4->setObjectName(QString::fromUtf8("btn_1_4"));
        btn_1_4->setEnabled(true);
        btn_1_4->setGeometry(QRect(330, 180, 50, 50));
        sizePolicy.setHeightForWidth(btn_1_4->sizePolicy().hasHeightForWidth());
        btn_1_4->setSizePolicy(sizePolicy);
        btn_1_4->setMinimumSize(QSize(50, 50));
        btn_1_4->setMaximumSize(QSize(60, 50));
        btn_1_4->setStyleSheet(QString::fromUtf8(""));
        btn_1_4->setFlat(true);
        btn_8_4 = new QPushButton(netpan);
        btn_8_4->setObjectName(QString::fromUtf8("btn_8_4"));
        btn_8_4->setEnabled(true);
        btn_8_4->setGeometry(QRect(330, 530, 50, 50));
        sizePolicy.setHeightForWidth(btn_8_4->sizePolicy().hasHeightForWidth());
        btn_8_4->setSizePolicy(sizePolicy);
        btn_8_4->setMinimumSize(QSize(50, 50));
        btn_8_4->setMaximumSize(QSize(60, 50));
        btn_8_4->setStyleSheet(QString::fromUtf8(""));
        btn_8_4->setFlat(true);

        retranslateUi(netpan);

        QMetaObject::connectSlotsByName(netpan);
    } // setupUi

    void retranslateUi(QWidget *netpan)
    {
        netpan->setWindowTitle(QCoreApplication::translate("netpan", "Form", nullptr));
        btn_1_6->setText(QString());
        btn_2_3->setText(QString());
        btn_7_5->setText(QString());
        btn_1_7->setText(QString());
        btn_5_5->setText(QString());
        btn_3_6->setText(QString());
        btn_1_0->setText(QString());
        btn_8_8->setText(QString());
        btn_8_3->setText(QString());
        btn_1_2->setText(QString());
        btn_8_5->setText(QString());
        btn_lose->setText(QCoreApplication::translate("netpan", "\350\256\244\350\276\223", nullptr));
        line_player_0->setText(QCoreApplication::translate("netpan", "\344\270\201\347\234\237", nullptr));
        btn_4_1->setText(QString());
        btn_7_2->setText(QString());
        btn_5_8->setText(QString());
        btn_6_6->setText(QString());
        btn_startgame->setText(QCoreApplication::translate("netpan", "\345\274\200\345\247\213\346\270\270\346\210\217", nullptr));
        btn_3_3->setText(QString());
        btn_6_5->setText(QString());
        btn_2_7->setText(QString());
        btn_6_4->setText(QString());
        btn_2_5->setText(QString());
        btn_2_1->setText(QString());
        btn_3_0->setText(QString());
        btn_0_1->setText(QString());
        btn_0_3->setText(QString());
        btn_5_1->setText(QString());
        btn_6_1->setText(QString());
        btn_1_5->setText(QString());
        btn_5_4->setText(QString());
        btn_7_8->setText(QString());
        btn_8_7->setText(QString());
        btn_2_4->setText(QString());
        btn_8_1->setText(QString());
        txtl_pan_time->setText(QString());
        btn_3_5->setText(QString());
        label->setText(QCoreApplication::translate("netpan", "\345\200\222\350\256\241\346\227\266\357\274\232", nullptr));
        btn_2_0->setText(QString());
        btn_2_2->setText(QString());
        btn_5_0->setText(QString());
        btn_2_8->setText(QString());
        btn_4_6->setText(QString());
        btn_white->setText(QString());
        btn_7_3->setText(QString());
        btn_5_6->setText(QString());
        btn_restart->setText(QCoreApplication::translate("netpan", "\351\207\215\346\226\260\345\274\200\345\247\213", nullptr));
        btn_2_6->setText(QString());
        btn_0_2->setText(QString());
        btn_1_1->setText(QString());
        btn_4_5->setText(QString());
        btn_3_4->setText(QString());
        btn_6_7->setText(QString());
        btn_4_7->setText(QString());
        btn_4_0->setText(QString());
        btn_8_0->setText(QString());
        btn_3_2->setText(QString());
        btn_0_0->setText(QString());
        btn_3_8->setText(QString());
        btn_0_7->setText(QString());
        label_3->setText(QCoreApplication::translate("netpan", "VS", nullptr));
        btn_7_1->setText(QString());
        btn_black->setText(QString());
        btn_0_5->setText(QString());
        btn_6_0->setText(QString());
        btn_0_4->setText(QString());
        btn_7_7->setText(QString());
        btn_4_2->setText(QString());
        btn_6_3->setText(QString());
        btn_5_7->setText(QString());
        btn_7_0->setText(QString());
        btn_6_8->setText(QString());
        btn_4_4->setText(QString());
        btn_4_3->setText(QString());
        btn_8_6->setText(QString());
        btn_6_2->setText(QString());
        btn_7_6->setText(QString());
        btn_stop->setText(QCoreApplication::translate("netpan", "\346\232\202\345\201\234\346\270\270\346\210\217", nullptr));
        back->setText(QCoreApplication::translate("netpan", "\345\220\216\351\200\200", nullptr));
        btn_3_7->setText(QString());
        btn_8_2->setText(QString());
        btn_1_8->setText(QString());
        btn_5_2->setText(QString());
        line_player_1->setText(QCoreApplication::translate("netpan", "\350\260\267\347\210\261\345\207\214", nullptr));
        btn_0_8->setText(QString());
        btn_7_4->setText(QString());
        btn_4_8->setText(QString());
        btn_0_6->setText(QString());
        btn_1_3->setText(QString());
        btn_3_1->setText(QString());
        btn_5_3->setText(QString());
        btn_1_4->setText(QString());
        btn_8_4->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class netpan: public Ui_netpan {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NETPAN_H
